brianlong/www.validators.app

- .gitignore
- Capfile
- Gemfile
- Gemfile.lock
- app/logic/pipeline_logic.rb
- config/deploy.rb
- config/schedule.rb
> 173321375 configure sidekiq

- app/controllers/public_controller.rb
- app/logic/report_logic.rb
- app/models/report.rb
- app/views/public/_skipped_after_table.html.erb
- app/views/public/_skipped_slots_table.html.erb
- app/workers/build_skipped_after_percent_worker.rb
- app/workers/build_skipped_slot_percent_worker.rb
- app/workers/build_top_skipped_slot_percent_worker.rb
- config/application.rb
- db/migrate/20200615000540_create_reports.rb
- db/schema.rb
- dev/report_logic_demo.rb
- script/gather_rpc_data.rb
- test/factories/reports.rb
- test/models/report_test.rb
Create the Report model + ReportLogic. Create a couple of SidekiqWorkers to create reports in the background.
> 173321327 report model

- app/controllers/public_controller.rb
- app/logic/report_logic.rb
- app/views/layouts/application.html.erb
- app/views/public/_chart_home_page.html.erb
- app/views/public/index.en.html.erb
- app/views/public/sample_chart.html.erb
- app/workers/chart_home_page_worker.rb
- config/routes.rb
- dev/create_home_page_chart.rb
- doc/color_pallette.txt
- script/gather_rpc_data.rb
Adds charting library & reports model.
> 173321330 charts

- app/logic/solana_logic.rb
- app/models/epoch_history.rb
- db/migrate/20200702212903_create_epoch_histories.rb
- db/schema.rb
- script/gather_rpc_data.rb
- test/factories/epoch_histories.rb
- test/logic/solana_logic_test.rb
- test/models/epoch_history_test.rb
- test/test_helper.rb
- test/vcr_cassettes/epoch_get.yml
Adds EpochHistory model and collects data with our pipeline.
> Adds EpochHistory model and collects data with our pipeline.

- app/controllers/public_controller.rb
- app/helpers/application_helper.rb
- app/logic/report_logic.rb
- app/logic/solana_logic.rb
- app/models/validator_history.rb
- app/views/public/_tower_table.html.erb
- app/views/public/index.en.html.erb
- app/views/public/tower.html.erb
- app/workers/report_tower_height_worker.rb
- config/routes.rb
- db/migrate/20200702220912_create_validator_histories.rb
- db/schema.rb
- dev/report_tower_height.rb
- script/gather_rpc_data.rb
- test/factories/validator_histories.rb
- test/logic/report_logic_test.rb
- test/logic/solana_logic_test.rb
- test/models/validator_history_test.rb
- test/vcr_cassettes/report_tower_height.yml
- test/vcr_cassettes/validators_cli.yml
Adds Validator data from CLI + Tower Reports
> Adds Validator data from CLI

- app/controllers/api/v1/api_controller.rb
- app/controllers/public_controller.rb
- app/controllers/validators_controller.rb
- app/logic/report_logic.rb
- app/logic/solana_logic.rb
- app/views/layouts/application.html.erb
- app/views/public/index.en.html.erb
- app/views/validators/index.html.erb
- app/workers/build_skipped_after_percent_worker.rb
- app/workers/build_skipped_slot_percent_worker.rb
- db/migrate/20200703190032_fix_network_batch.rb
- db/schema.rb
- script/gather_rpc_data.rb
Consistent treatment of :network & :batch_uuid attributes.
> 20200703 network updates

- app/controllers/validators_controller.rb
- app/logic/report_logic.rb
- app/views/validators/index.html.erb
- app/workers/report_software_version_worker.rb
- script/gather_rpc_data.rb
- script/gather_rpc_data_mainnet.rb
- test/fixtures/vote_account_histories.yml
- test/logic/report_logic_test.rb
Adds a software version report
> Group software version

- app/logic/solana_logic.rb
- config/schedule.rb
- db/migrate/20200729033136_add_validator_info.rb
- db/schema.rb
- script/validators_get_info.rb
Adds a script to get Validator info in the background
> Adds a script to get Validator info in the background

- app/controllers/validators_controller.rb
- app/views/validators/index.html.erb
- config/schedule.rb
- script/archive_for_restart.rb
> Deal with restarts

- app/controllers/api/v1/api_controller.rb
- app/controllers/api/v1/base_controller.rb
- app/views/api/v1/validators/_validator.json.jbuilder
- app/views/public/api_documentation.html.erb
Revise the API to show more valdiator data
> Revise the API to show more valdiator data

- app/controllers/application_controller.rb
- app/controllers/public_controller.rb
- app/views/validators/index.html.erb
- app/views/validators/show.html.erb
- app/views/vote_accounts/show.html.erb
Remove the old front page and use the list of validators instead
> Remove the old front page and use the list of validators instead

- app/controllers/public_controller.rb
- app/views/validators/index.html.erb
> Validator search form

- app/logic/solana_logic.rb
- app/views/api/v1/validators/_validator.json.jbuilder
- db/migrate/20210202032238_add_data_center_host_to_scores.rb
- db/schema.rb
- script/fix_ip_hetzner.rb
- script/validators_get_info.rb
- Adds data_center_host to the current API endpoint
> 20210201 data center hosts

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cards.scss
- app/assets/stylesheets/images.scss
- app/assets/stylesheets/tables.scss
- app/views/data_centers/data_center.html.erb
- app/views/validators/_block_history_chart.html.erb
- app/views/validators/_block_history_table.html.erb
- app/views/validators/_sort_bar.erb
- app/views/validators/_spark_line_block_vote.html.erb
- app/views/validators/index.html.erb
- app/views/validators/show.html.erb
> Validators show view

- config/schedule.rb
- db/migrate/20210325011353_add_aso_to_ip_overrides.rb
- db/schema.rb
- script/concerns/fix_ip_module.rb
- script/fix_ip_hetzner.rb
- script/fix_ip_ovh.rb
Updates ip details of the validators from OVH datacenters
bundle exec rails r script/fix_ip_ovh.rb
https://www.pivotaltracker.com/story/show/177409186
> 177409186 fix ips hetzner ovh

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/cards.scss
- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/forms.scss
- app/assets/stylesheets/pagination.scss
- app/assets/stylesheets/variables.scss
- app/views/data_centers/data_center.html.erb
- app/views/data_centers/index.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/public/_form_contact_us.html.erb
- app/views/validators/_banner.html.erb
- app/views/validators/_form.html.erb
- app/views/validators/_sort_bar.erb
- app/views/validators/_stats.html.erb
- app/views/validators/index.html.erb
- app/views/validators/show.html.erb
- app/views/vote_accounts/show.html.erb
- app/views/you/index.html.erb
- Aligns links to charts in one row
- https://www.pivotaltracker.com/n/projects/2177859/stories/177480279
- 
> 177480279 stop line wrap on mobile

- app/assets/stylesheets/application.scss
- app/views/validators/show.html.erb
- Run app and check validator show page
- https://www.pivotaltracker.com/n/projects/2177859/stories/177525194
> 177525194 display delinquency status

- app/controllers/validators_controller.rb
- app/views/validators/_block_history_chart.html.erb
- app/views/validators/_spark_line_skipped_slots.html.erb
- app/views/validators/index.html.erb
- Display MA stats
- Calculate skipped slot % score based on MA number
> Show ma stats 177163675 skipped slots moving avg

- app/controllers/validators_controller.rb
- app/views/validators/_block_history_chart.html.erb
- app/views/validators/_spark_line_skipped_slots.html.erb
- app/views/validators/index.html.erb
Reverts brianlong/www.validators.app#66
> Revert "Show ma stats 177163675 skipped slots moving avg"

- app/assets/stylesheets/tables.scss
- app/controllers/public_controller.rb
- app/views/validators/index.html.erb
add a 33% line to 'Stake' view
check the line on the root page (order by stake)
https://www.pivotaltracker.com/story/show/177711685
> 177711685 stake halt line

- app/logic/solana_logic.rb
- app/logic/validator_score_v1_logic.rb
- app/models/batch.rb
- app/views/validators/show.html.erb
- config/deploy.rb
- config/schedule.rb
- daemons/validator_score_mainnet_v1.service
- daemons/validator_score_mainnet_v1_daemon.rb
- daemons/validator_score_mainnet_v1_notes.txt
- daemons/validator_score_testnet_v1.service
- daemons/validator_score_testnet_v1_daemon.rb
- db/migrate/20210416133005_add_scored_at_to_batch.rb
- db/schema.rb
- script/gather_rpc_data.rb
- script/gather_rpc_data_mainnet.rb
Moves the scoring task out of Sidekiq into a background daemon. I see much better performance now.
> 177792938 score daemon

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/images.scss
- app/assets/stylesheets/tables.scss
- app/helpers/application_helper.rb
- app/models/validator.rb
- app/models/validator_score_v1.rb
- app/views/validators/_scores.html.erb
- app/views/validators/index.html.erb
- app/views/validators/show.html.erb
- db/schema.rb
- script/validators_get_info.rb
- test/models/validator_score_v1_test.rb
- test/models/validator_test.rb
- Adds "Private Validator" information
- https://www.pivotaltracker.com/n/projects/2177859/stories/178014329/comments/223969559
> 178014329 private node zero points

- app/views/validators/index.html.erb
- Hides commission (100%) for private validators - only for index view.
- Update some validator with commission == 100 (must be in mainnnet network)
- check index view
- https://www.pivotaltracker.com/n/projects/2177859/stories/178085179
> 178085179 hide commission for private validators

- app/models/batch.rb
- app/models/collector.rb
- app/models/contact_request.rb
- app/models/epoch_history.rb
- app/models/ip.rb
- app/models/ip_override.rb
- app/models/ping_time.rb
- app/models/ping_time_stat.rb
- app/models/report.rb
- app/models/user.rb
- app/models/validator.rb
- app/models/validator_block_history.rb
- app/models/validator_block_history_stat.rb
- app/models/validator_history.rb
- app/models/validator_ip.rb
- app/models/validator_score_v1.rb
- app/models/vote_account.rb
- app/models/vote_account_history.rb
- db/schema.rb
- Update collation to utf8mb4_0900_ai_ci in schema.rb
- Run migration, check if there is no changes in schema.rb
- Remember to add 
``` 
encoding: utf8mb4
collation: utf8mb4_0900_ai_ci
```
to your database.yml (you need to have mysql 8.0 installed or higher version for this collationj)
- https://www.pivotaltracker.com/story/show/178177826
> 178177826_update_schema_rb

- app/controllers/api/v1/api_controller.rb
- app/controllers/public_controller.rb
- app/controllers/validators_controller.rb
- app/helpers/validators_helper.rb
- app/logic/validator_score_v1_logic.rb
- app/models/batch.rb
- app/models/validator.rb
- app/models/validator_history.rb
- app/models/validator_score_v1.rb
- app/models/vote_account_history.rb
- app/queries/application_query.rb
- app/queries/validator_block_history_query.rb
- app/queries/validator_history_query.rb
- app/queries/validator_search_query.rb
- app/queries/vote_account_history_query.rb
- app/views/public/faq.en.html.erb
- app/views/validators/_scores.html.erb
- app/views/validators/index.html.erb
- test/controllers/validators_controller_test.rb
- test/factories/validator_histories.rb
- test/factories/validators.rb
- test/logic/validator_score_v1_logic_test.rb
- test/queries/validator_block_history_query_test.rb
- test/queries/validator_history_query_test.rb
- test/queries/validator_search_query_test.rb
- test/queries/vote_account_history_query_test.rb
- Add queries to handle class query methods
- Calculate top 33% of stake possesion
- Run tests
https://www.pivotaltracker.com/story/show/177911305
> 177911305 improve stake concentration score

- app/views/validators/_sort_bar.erb
- Removes 'name' and 'random' options from view, keeps the logic in case we want to bring them back in future
- Use sort options on homepage
- https://www.pivotaltracker.com/n/projects/2177859/stories/178459409
> 178459409 drop name and random search options

- app/controllers/api/v1/api_controller.rb
- app/views/api/v1/validators/_validator.json.jbuilder
- test/controllers/api/v1/api_controller_test.rb
- test/factories/reports.rb
- test/factories/validator_score_v1s.rb
- test/factories/validators.rb
- test/factories/vote_accounts.rb
- Add tests to check response body, update factories
- Run tests
- https://www.pivotaltracker.com/story/show/178368635
> 178368635_test_coverage_for_api

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/api_controller.rb
- app/controllers/data_centers_controller.rb
- config/environments/development.rb
- config/environments/test.rb
- Find n+1 queries
- Run tests
- https://www.pivotaltracker.com/story/show/178469553
> 178469553_install_bullet_gem_to_find_n_1_queries

- app/controllers/api/v1/api_controller.rb
- test/controllers/api/v1/api_controller_test.rb
- Bring back joins instead of left_outer_join
- Run tests
- https://www.pivotaltracker.com/story/show/178368635
> 178368635_check_test_coverage_bring_back_previous_behaviour

- app/controllers/public_controller.rb
- app/controllers/validators_controller.rb
- app/helpers/validators_helper.rb
- app/logic/validator_score_v1_logic.rb
- app/models/batch.rb
- app/models/vote_account_history.rb
- app/queries/vote_account_history_query.rb
- app/views/validators/_spark_line_skipped_vote.html.erb
- app/views/validators/index.html.erb
- db/migrate/20210610104446_add_skipped_vote_fields_to_batches.rb
- db/schema.rb
- test/logic/validator_score_v1_logic_test.rb
- test/models/vote_account_history_test.rb
reduce the load on the index page by moving skipped_vote calculations to validator_score_v1_logic
check if the numbers and charts are correct on the main page
https://www.pivotaltracker.com/story/show/178318190
> 178318190 skipped vote median and average calculated in backround

- app/assets/stylesheets/tables.scss
- app/controllers/asns_controller.rb
- app/controllers/data_centers_controller.rb
- app/views/asns/show.html.erb
- app/views/data_centers/data_center.html.erb
- app/views/validators/_as_row.html.erb
- app/views/validators/_basic_list.html.erb
asn and data center views should have lists of validators similar to the index view
with speedometers. Additionally there should be info about IP and data center host 
for each validator (if available)
In order to see the asn/data centers it's necessary to update ips by running
script/append_ip_geo_data.rb
https://www.pivotaltracker.com/story/show/178588216
> ASN and Data center views with speedometers

- app/models/validator.rb
- app/queries/validator_score_query.rb
- test/queries/validator_score_query_test.rb
Fix https://appsignal.com/first-movers-advantage-llc/sites/5ee553e80264447914683971/exceptions/incidents/176
Ticket: https://www.pivotaltracker.com/story/show/178085341
> 178085341-cluster-stats-view-handle-nil

- app/controllers/asns_controller.rb
- app/controllers/data_centers_controller.rb
- app/views/asns/show.html.erb
- app/views/data_centers/data_center.html.erb
- app/views/validators/_basic_list.html.erb
adds pagination to show views for data centers and asns
look for pagination in above views
https://www.pivotaltracker.com/story/show/178676837
> 178676837 add pagination to data centers and asns

- script/fix_ip_hetzner.rb
Update fix_ip_hetzner script to work with the last matching line from traceroute, not the first
run fix_ip_hetzner.rb (you need to have ips in your db)
https://www.pivotaltracker.com/story/show/178677314
> script uses fix_ip_module

- app/logic/solana_logic.rb
- daemons/gather_rpc_mainnet_daemon.rb
- daemons/gather_rpc_testnet_daemon.rb
- test/logic/solana_logic_test.rb
- test/vcr_cassettes/check_epoch.yml
- Add epoch flag to block-production request
- Add new step that checks epoch at the and of the pipeline
- Run tests
- https://www.pivotaltracker.com/story/show/178625382
> 178625382_block_history_bug

- test/workers/validator_check_active_worker_test.rb
- Skip failing test for now
- Run tests
- https://www.pivotaltracker.com/story/show/178772761
> 178772761_fix_test_suite

- app/controllers/api/v1/api_controller.rb
- test/controllers/api/v1/api_controller_test.rb
- Add page param + test
- Run tests
- Run server and send request from ie. postman with limit and page params (`http://www.localhost:3000/api/v1/validators/mainnet.json?limit=5&page=3"`)
- https://www.pivotaltracker.com/story/show/178765875
> 178765875_add_pagination_to_endpoint

- app/controllers/api/v1/api_controller.rb
- test/controllers/api/v1/api_controller_test.rb
- Add search query to api
- Run tests
- Run server and send request from ie. postman with limit and page params (http://www.localhost:3000/api/v1/validators/mainnet.json?q=searchtext")
- https://www.pivotaltracker.com/story/show/178765879
> 178765879_add_search_feature_to_api

- app/helpers/validators_helper.rb
- app/logic/validator_score_v1_logic.rb
- app/views/validators/_software_versions.html.erb
- test/logic/validator_score_v1_logic_test.rb
find leading software version with changed algorithm
display sorted versions on the index page
- check if versions on the home page are sorted from highest stake to lowest
- check if correct leading version is marked green
https://www.pivotaltracker.com/story/show/178766004
> fix software version algorithm

- app/views/public/api_documentation.html.erb
- Add docs about q and page param
- https://www.pivotaltracker.com/story/show/178798724
> 178798724_update_api_docs

- app/assets/stylesheets/tables.scss
- app/views/validators/_basic_list.html.erb
- Simple fix, see story description in PT
- https://www.pivotaltracker.com/n/projects/2177859/stories/178802633
> 178802633 Fix rendering validators table on narrow desktop screens

- app/controllers/public_controller.rb
- app/models/batch.rb
- app/models/commission_history.rb
- app/models/validator.rb
- app/models/validator_history.rb
- app/models/validator_score_v1.rb
- app/services/create_commission_history_service.rb
- app/views/layouts/_footer.html.erb
- app/views/public/_commission_changed_indicator.html.erb
- app/views/public/commission_histories.html.erb
- app/views/validators/show.html.erb
- config/routes.rb
- db/migrate/20210708073955_create_commission_histories.rb
- db/migrate/20210708133030_add_network_to_commission_histories.rb
- db/migrate/20210708140201_add_epoch_info_to_commission_history.rb
- db/migrate/20210709093055_add_index_on_network_to_batches.rb
- db/schema.rb
- test/factories/commission_histories.rb
- test/models/commission_history_test.rb
- test/models/validator_history_test.rb
- test/models/validator_score_v1_test.rb
- test/services/create_commission_history_service_test.rb
commission_history should be created every time the commission is changed for the validator
run score and gather scripts, check if commission_histories are being created
and if the data is correct
https://www.pivotaltracker.com/story/show/178792573
>  178792573-commission-change-report

- app/helpers/validators_helper.rb
software_versions should be sorted correctly on the index page
see the software versions on home page, check if sorting by version is correct
https://www.pivotaltracker.com/story/show/178799307
> 178799307 fix software_version sorting

- app/views/validators/show.html.erb
- As in title
- https://www.pivotaltracker.com/n/projects/2177859/stories/178883647
- https://www.pivotaltracker.com/n/projects/2177859/stories/178883475
-
> 178883647 small tweaks for validator show page

- app/controllers/public_controller.rb
- app/queries/validator_search_query.rb
- app/views/validators/_software_versions.html.erb
- test/queries/validator_search_query_test.rb
software versions on the bottom of home page should be clickable - after click 
there should be validators filtered by given version
- run tests
- check if links work properly
https://www.pivotaltracker.com/story/show/178881010
> 178881010 filter by software version

- app/controllers/api/v1/api_controller.rb
- Add fields and select statement 
- Make a request to ie. https://stage.validators.app/api/v1/validators/testnet.json (or localhost), check response time.
- https://www.pivotaltracker.com/story/show/178962732
> 178962732_select_only_needed_fields_in_api_query

- app/logic/report_logic.rb
- app/views/validators/show.html.erb
- test/logic/report_logic_test.rb
- Use software_version from score on validator show page
- See the show page of the one of the validators to see if software version is correctly displayed
- Run the daemons, see if there are no errors
- https://www.pivotaltracker.com/story/show/178910745
> 178910745_fix_displayed_validator_software_version

- app/logic/report_logic.rb
- app/views/validators/show.html.erb
- test/logic/report_logic_test.rb
Reverts brianlong/www.validators.app#161
Related to: https://appsignal.com/first-movers-advantage-llc/sites/5ee553e80264447914683971/exceptions/incidents/26
> Revert "178910745_fix_displayed_validator_software_version"

- app/controllers/api/v1/api_controller.rb
- Update query, add new fields to pull out to join correctly
- Make a request to ie. https://stage.validators.app/api/v1/validators/testnet.json (or localhost), check response time
- https://www.pivotaltracker.com/story/show/178971561
> 178971561_add_select_with_fields_specified_to_validators_show

- app/controllers/validators_controller.rb
- app/logic/solana_logic.rb
- app/models/validator_history.rb
- app/views/validators/_block_history_table.html.erb
- db/migrate/20210725174729_add_max_height_colums_to_validator_history.rb
- db/schema.rb
- script/back_fill_validator_histories.rb
- Removes the N+1 queries on the distance charts
> 178993763 reduce n plus one

- app/controllers/api/v1/api_controller.rb
- app/models/ip.rb
- app/models/validator_score_v1.rb
- app/views/api/v1/validators/_validator.json.jbuilder
- test/models/ip_test.rb
- test/models/validator_score_v1_test.rb
- Load all needed ips in controller
- Make a request to ie. https://stage.validators.app/api/v1/validators/testnet.json (or localhost), check response time
- https://www.pivotaltracker.com/story/show/178962750
> 178962750_deal_with_ip

- app/logic/report_logic.rb
- test/helpers/validators_helper_test.rb
- test/logic/report_logic_test.rb
- Fix problem with malformed versions
- Run tests
- https://www.pivotaltracker.com/story/show/179000784
> 179000784_re_fix_action_view_template_error

- app/logic/solana_logic.rb
- app/models/vote_account_history.rb
- dev/solana_pipeline_demo.rb
all validators should have proper charts without double validator_history
- check if there's only one validator_history for each batch and validator
- check if charts look ok
https://www.pivotaltracker.com/story/show/179000241
>  179000241-re-fix-charts

- app/controllers/api/v1/api_controller.rb
- app/views/public/api_documentation.html.erb
- app/views/public/faq.en.html.erb
- test/controllers/api/v1/api_controller_test.rb
- Removes the old ping times feature from the API
- The feature was removed. Nothing to test.
> Removes ping times feature

- app/controllers/public_controller.rb
- app/logic/report_logic.rb
- test/controllers/public_controller_test.rb
- test/logic/report_logic_test.rb
- Add query to get correct software versions to report
- Run tests
- Check software scores at the bottom of the homepage
- https://www.pivotaltracker.com/story/show/179034755
> 179034755_fix_software_version_table

- app/controllers/validators_controller.rb
- app/views/validators/_block_history_table.html.erb
remove query from views to improve performance
validator show page should work a bit faster
https://www.pivotaltracker.com/story/show/178988670
> 178988670 validators show performance

- daemons/gather_rpc_mainnet_daemon.rb
- daemons/gather_rpc_testnet_daemon.rb
- sleep a minute  on 500 while gathering the data in daemons
https://www.pivotaltracker.com/story/show/179028443
> 179028443 Sleep on 503 solana-rpc

- Gemfile.lock
- Bump solana_rpc_ruby to 1.0.1
- https://www.pivotaltracker.com/story/show/178970315
> 178970315_update_solana_rpc_ruby_to_1_0_1

- app/logic/validator_score_v1_logic.rb
- app/models/validator_score_v1.rb
- As in title and PT story description
- Deploy to staging, let it process a new batch, and check the difference in scores for this validator: https://www.validators.app/validators/mainnet/GXbz6pX6TKWv3XhQYpjJt2hg9Jjo1wZ2r7coV7AeK42f?locale=en
- https://www.pivotaltracker.com/n/projects/2177859/stories/179217573
> 179217573 fix median and average period in score

- app/views/validators/_banner.html.erb
- app/views/validators/_no_search_results.html.erb
- app/views/validators/index.html.erb
if no results were returned in search, add option to return to root
search for random text, if there are no results there should be info about it and a button to reset filters
https://www.pivotaltracker.com/story/show/178910236
> 178910236-reset-search-filters

- script/concerns/fix_ip_module.rb
attempt to remove dedlocks for long query
error occurs only production, so we will need to deploy to test it out
https://www.pivotaltracker.com/story/show/178676857
> 178676857-deadlocks-for-hetzner-script

- app/assets/stylesheets/pagination.scss
- app/javascript/packs/commission_histories/commission_history_row.js
- app/javascript/packs/commission_histories/index.js
- app/javascript/packs/commission_histories/index_template.vue
- Add filtering by validator
- Add icon to open validator page in new tab
- Open commision changes page
- Click on validator name to see if results are filtered 
- Click on the icon, check if new validator page is being opened in new tab
- https://www.pivotaltracker.com/story/show/179268304
> 179268304_filter_results_in_commission_changes_table

- app/controllers/api/v1/api_controller.rb
- app/models/epoch_history.rb
- test/controllers/api/v1/api_controller_test.rb
- Add epoch to api response
- Run tests
- Send request to API, check if epoch field is present
- https://www.pivotaltracker.com/story/show/179359356
> 179359356_add_current_epoch

- app/controllers/api/v1/api_controller.rb
- Add network to get correct current_epoch
- Run tests
- https://www.pivotaltracker.com/story/show/179359356
> 179359356_add_network_to_current_epoch

- app/views/validators/_search_bar.html.erb
- Add more descriptive hint to search bar
- See the placeholder on the main page
- https://www.pivotaltracker.com/story/show/179657491
- 
> 179657491_add_more_descriptive_hint_to_search

- app/views/validators/_software_versions.html.erb
- Change header to make it more meaningful
- 
- Run server
- Open `Cluster stats`
- See if the heading is changed
- https://www.pivotaltracker.com/story/show/179657492
> 179657492_change_count_in_software_version_report_to_sth_more_meaningful

- app/controllers/application_controller.rb
- app/javascript/packs/navigation/network_buttons.js
- app/javascript/packs/navigation/network_buttons_template.vue
- app/views/layouts/_header.html.erb
- package.json
- yarn.lock
header links for mainnet/testnet don't redirect to homepage, but changes the network on the current page instead
visit different pages and try the buttons
https://www.pivotaltracker.com/story/show/179657493
> 179657493 change behaviour of network links

- app/assets/stylesheets/tables.scss
- app/javascript/packs/application.js
- app/views/cluster_stats/index.html.erb
- app/views/data_centers/_asn_head.html.erb
- app/views/data_centers/_data_center_head.html.erb
- app/views/validators/index.html.erb
- config/locales/en.yml
- Add tooltips to some part of the page to explain our system better
- Go to the changed views, check the info displayed
- Check the definitions, feel free to improve
- https://www.pivotaltracker.com/story/show/179657490
> 179657490_more_descriptive_pop_ups_hints

- app/views/validators/_banner.html.erb
- Add Lido and Socean links
- Check headline on the front page, click on the Lido and Socean link
- https://www.pivotaltracker.com/story/show/179624441
> 179740168_add_lido_and_socean

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/header.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- config/locales/en.yml
changed navbar layout - login buttons moved to footer, faq and stats moved to header
see the header on the landing page
https://www.pivotaltracker.com/story/show/179658041
> 179658041-new-top-navbar-layout

- app/views/layouts/_footer.html.erb
- Sign in, then sign out. Check footer links.
- https://www.pivotaltracker.com/n/projects/2177859/stories/179801470
> 179801470 Fix sign out class

- app/views/layouts/_footer.html.erb
data centers link in footer
see the footer
https://www.pivotaltracker.com/story/show/179800760
> 179800760-data-center-link-in-footer

- app/javascript/packs/commission_histories/commission_history_row.js
- app/javascript/packs/navigation/network_buttons_template.vue
- config/routes.rb
remove all /:network paths from routes and use param instead
- click thorugh the page and make sure all links work as expected
- run tests
https://www.pivotaltracker.com/story/show/179738766
> 179738766 unify network params

- app/services/sorted_data_centers.rb
- app/views/data_centers/_asn_list.html.erb
Ip's with nil asn causes error on asn index page, so these should be rejected
create an IP object without autonomous system number and see if 
/data-centers?locale=en&network=testnet&sort_by=asn is working
https://www.pivotaltracker.com/story/show/180113422
> 180113422-fix-data-centers-asn-error

- app/controllers/asns_controller.rb
- app/controllers/data_centers_controller.rb
- app/views/asns/show.html.erb
- app/views/data_centers/data_center.html.erb
population and active stake should be calculated for all validators in asn and data center
check population and total stake in show pages (asn and data center)
https://www.pivotaltracker.com/story/show/180011409
> 180011409-fix-asn-population

- app/views/public/faq.en.html.erb
- add info about score of private validators
- check getting started page
https://www.pivotaltracker.com/story/show/180084997
> 180084997-add-info-about-private-validators-score

- app/logic/asn_logic.rb
- Create log dir if doesn't exist
- Run added code in console, it should create logger without error (remove directory if exists). 
- https://www.pivotaltracker.com/story/show/180178875
> 180178875_asn_logger_not_being_created

- app/logic/asn_logic.rb
- dev/asn_logic_demo.rb
- Add guard clause
- Run `bundle exec rails r dev/asn_logic_demo.rb` 
- https://www.pivotaltracker.com/story/show/180178631
> 180178631_fix_asn_averages_for_testnet

- app/javascript/packs/commission_histories/commission_history_row.js
- Add title attribue with hint to links
- See the screenshots on PT story.
- https://www.pivotaltracker.com/story/show/179908116
> 179908116_add_hints_for_links

- app/helpers/validators_helper.rb
- app/views/validators/_table.html.erb
- Make an avatar a link to validator show page
- Go to validators index page and try to click on avatar, it should redirect you to validator's show page.
- https://www.pivotaltracker.com/story/show/180029023
> 180029023_make_a_validator_avatar_clickable

- app/controllers/asns_controller.rb
- app/controllers/data_centers_controller.rb
- app/models/validator_score_v1.rb
- app/views/asns/show.html.erb
- app/views/data_centers/_asn_list.html.erb
- app/views/data_centers/_data_center_list.html.erb
- app/views/data_centers/data_center.html.erb
- test/models/validator_score_v1_test.rb
add filtering by delinquent and inactive in data centers and asns views
- data center show and asn show pages should have filtering working correctly
- in the index pages (for data centers / asns) delinquent number should be a link to filter
https://www.pivotaltracker.com/story/show/179922946
> 179922946-add-delinquent-filtering-in-data-centers

- app/controllers/validators_controller.rb
- app/queries/commission_history_query.rb
- app/views/validators/show.html.erb
- ADd correct checking for commission historiesbefore displaying link
- Deploy to staging and check the links from the description in PT story (or try to do it on localhost)
- https://www.pivotaltracker.com/story/show/180178401
> 180178401_no_commission_changes_visible

- app/models/validator_score_v1.rb
- app/views/data_centers/data_center.html.erb
fix data centers show
check if there are correct number of validators in data centers detail page, and if filtering works as expected
https://www.pivotaltracker.com/story/show/180318179
> 179922946-fix

- app/controllers/api/v1/commission_histories_controller.rb
- app/views/public/api_documentation.html.erb
- add `page` and `per` parameters to docs for commission histories
- check if docs are there
- check pronunciation
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180348219)
> 180348219-update-commission-api-docs

- script/assign_data_center_scores.rb
Change data concentration factor from 25% to 10%
run script/assign_data_center_scores.rb
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180328011)
> change 25% to 10%

- app/services/sorted_data_centers.rb
- app/views/data_centers/_asn_head.html.erb
- app/views/data_centers/_asn_list.html.erb
- app/views/data_centers/_data_center_head.html.erb
- app/views/data_centers/_data_center_list.html.erb
- config/locales/en.yml
- Add private column to data centers view
- Go to http://localhost:3000/data-centers?locale=en&network=mainnet and check 'Private' column (it should be only visible for mainnet)
- Change to ASN view and check as well
- https://www.pivotaltracker.com/story/show/179932924
- 
> 179932924_show_private_validators_metric_alongside_delinquent

- app/logic/stake_logic.rb
fix pulling stake_pools
- run script and check if stake pools are there
> add network to deleting history accounts

- app/models/validator.rb
- app/models/validator_score_v1.rb
- app/views/public/faq.en.html.erb
- app/views/validators/_scores.html.erb
- test/models/validator_score_v1_test.rb
- Add authorized withdrawer score to total score
- Check the validators index page, where you can see new circle with authorized witdrawer score
- Check the faq
- https://www.pivotaltracker.com/story/show/180331945
> 180331945_add_authorized_withdrawer_score_to_total_score

- app/controllers/api/v1/stake_accounts_controller.rb
- app/javascript/packs/stake_accounts/index_template.vue
- app/logic/stake_logic.rb
- app/views/api/v1/stake_accounts/index.json.jbuilder
- test/controllers/api/v1/stake_accounts_controller_test.rb
- get the stake pools from db instead of hardcode
- run `rails add_stake_pool:testnet`
- run `rails r dev/stake_logic_demo.rb`
- check if there's a correct button under withdrawer field in `/stake_accounts?network=testnet` page
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180423525)
> 180423525-stake-account-improvements

- app/models/stake_pool.rb
- db/migrate/20211130082418_add_ticker_to_stake_pools.rb
- db/schema.rb
- lib/tasks/add_stake_pools.rake
- add ticker to stake pool and add data to db
- run `rails add_stake_pool:mainnet` and see if there are stake_pools with populated ticker info
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180459084)
> 180459084-stake-pool-ticker

- daemons/validator_score_mainnet_v1_daemon.rb
- daemons/validator_score_testnet_v1_daemon.rb
> add _ to worker payload

- script/prune_database_tables.rb
- remove old records in db after 60 days instead of 30
> 180553625-60-days-data-retention

- config/webpacker.yml
- As in title
- Test on staging
> Remove deprecated option

- app/javascript/src/sol_prices_charts.js
- Fix js error by removing not needed function
- Visit http://localhost:3000/sol_prices?exchange=coin_gecko&filtering=7&locale=en&network=testnet and check all exchanges with all days filtering, check console and chart generation
- https://www.pivotaltracker.com/story/show/180494618
> 180494618_fix_type_error

- app/javascript/packs/commission_histories/index_template.vue
- app/views/public/commission_histories.html.erb
- app/views/public/faq.en.html.erb
- Adds some information to FAQ
- Review in browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180560658)
> 180560658 update faq

- config/deploy.rb
- Add task to deploy.rb to update fees
- 
- https://www.pivotaltracker.com/story/show/180571019
> 180571019_add_task_to_capistrano

- .github/workflows/test_suite.yml
- Remove mysql host verification
- Check gh actions output
- https://www.pivotaltracker.com/story/show/180619231
> 180619231_temp_fix

- app/controllers/api/v1/base_controller.rb
- app/helpers/application_helper.rb
- app/javascript/packs/stake_accounts/stake_account_row.js
- app/models/stake_account.rb
- app/views/api/v1/stake_accounts/_stake_account_detail.json.jbuilder
- app/views/api/v1/stake_accounts/index.json.jbuilder
- test/controllers/api/v1/stake_accounts_controller_test.rb
- test/helpers/application_helper_test.rb
- test/models/stake_account_test.rb
- Uses comma as a delimiterfor thousands + display only two decimal places
- 
- Go to `localhost:3000/stake_accounts` and check how sols in first columns are displayed (they should be delimited by thousands and have 2 decimal places)
- https://www.pivotaltracker.com/story/show/180570785
> 180570785_change_price_format

- app/logic/stake_logic.rb
- app/models/stake_account.rb
- app/models/stake_account_history.rb
- app/models/stake_pool.rb
- config/deploy.rb
- db/migrate/20211215082149_add_average_lifetime_to_stake_pools.rb
- db/schema.rb
- test/logic/stake_logic_test.rb
- Add average lifetime of validators to stake pools
- run dev/stake_logic_demo.rb and check if average_lifetime is populated.
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180555065)
> 180555065-average-validator-lifetime-in-stake-pools

- app/javascript/packs/stake_accounts/stake_account_row.js
- test/controllers/api/v1/stake_accounts_controller_test.rb
- change delegated stake to active stake in stake pool views
- see if the /stake_accounts view is working properly and first column with amount of SOLs is populated
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180576176)
> 180576176-stake-pool-credits-field

- app/services/solana_rpc_client.rb
- Fix broken methods, adds some comments
- Run tests
- https://www.pivotaltracker.com/story/show/179907326
> 179907326_fix_methods_in_solana_rpc_client

- app/helpers/data_centers_helper.rb
- app/views/asns/show.html.erb
- app/views/data_centers/data_center.html.erb
- Dynamically create links for filters 
- Go to `http://localhost:3000/data-centers?locale=en&network=mainnet&sort_by=data_center`
- Choose one of the data centers in both data centers and asn tabs
- Check if filtering works correctly
- https://www.pivotaltracker.com/story/show/180493072
> 180493072_create_method_in_helper

- lib/tasks/add_stake_pools.rake
- add DAOpool to rake task
- run rails add_stake_pool:mainnet and see if new stake pool is added
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180699155)
> 180699155-add-DAOpool

- config/routes.rb
- As in title
- Click through /stake-pools page in the browser
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180890659)
> 180890659 Change stake pools url

- app/javascript/packs/stake_accounts/charts/skipped_vote_speedometer.js
- Give up using not supported js function
- Review in the browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180891061)
> 180891061 Fix displaying stake pools on old browsers

- config/schedule.rb
- script/concerns/fix_ip_module.rb
- script/fix_ip_webnx.rb
- fix webnx ip data
- run script/append_ip_geo_data.rb (keep in mind development mode)
- run script/fix_ip_webnx.rb
- check if new IpOverride's are created and if the IP's were updated
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180772521)
> 180772521 fix webnx ip

- lib/tasks/add_stake_pools.rake
- add dao ticker
- run rails add_stake_pool:mainnet and check if daopool has a ticker
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180946638)
> 180946638-dao-ticker

- app/logic/stake_logic.rb
- dev/stake_logic_demo.rb
- script/gather_stake_accounts.rb
- test/factories/stake_accounts.rb
- test/logic/stake_logic_test.rb
- test/vcr_cassettes/stake_logic_get_rewards.yml
- change the way the apy is counted
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180890602)
> 180890602 different apy counting

- Gemfile.lock
- Bump solana_rpc_ruby gem to 1.2.0
-https://www.pivotaltracker.com/story/show/180872688
> 180872688_upgrade_solana_rpc_ruby_gem

- app/views/validators/_banner.html.erb
- as in title
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180963923)
> 180963923 Add link to stake pools on homepage

- app/controllers/api/v1/stake_accounts_controller.rb
- app/controllers/api/v1/stake_pools_controller.rb
- app/javascript/packs/stake_accounts/index_template.vue
- app/views/api/v1/stake_accounts/index.json.jbuilder
- app/views/api/v1/stake_pools/index.json.jbuilder
- app/views/public/api_documentation.html.erb
- config/routes.rb
- test/controllers/api/v1/stake_accounts_controller_test.rb
- test/controllers/api/v1/stake_pools_controller_test.rb
- Adds stake-pools api endpoint, updates stake-accounts api endpoint
> 180879195_stake_pools_api

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/pool_stats.js
- add average stake to stake pools
- go to /stake-pools and check the new stat
- check the stat explanation on the bottom
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180990818)
> 180990818-avg-stake

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/pool_stats.js
> 180990818 avg stake

- app/javascript/packs/navigation/network_buttons_template.vue
- app/javascript/packs/stake_accounts/charts/root_distance_chart.js
- app/javascript/packs/stake_accounts/charts/skipped_slot_chart.js
- app/javascript/packs/stake_accounts/charts/skipped_vote_speedometer.js
- app/javascript/packs/stake_accounts/charts/vote_distance_chart.js
- app/javascript/packs/stake_accounts/validator_row.js
- links to charts should display them on mobile version
- check if links to charts in /stake-pools work as they should on mobile version
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180962203)
> working charts

- lib/tasks/add_stake_pools.rake
- run rake tasks :
```
bundle exec rake add_stake_pool:mainnet
bundle exec rake update_fee_in_stake_pools:mainnet
```
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180982457)
> 180982457 Update socean manager fee

- app/controllers/api/v1/stake_accounts_controller.rb
- Bring back random order
-Go to http://localhost:3000/stake-pools?network=testnet, refresh page, check if order is random
- https://www.pivotaltracker.com/story/show/180991860
> 180991860_fix_random_order

- app/javascript/packs/stake_accounts/stake_account_row.js
- app/queries/stake_account_query.rb
- app/views/api/v1/stake_accounts/_stake_account_detail.json.jbuilder
- test/controllers/api/v1/stake_accounts_controller_test.rb
- test/queries/stake_account_query_test.rb
- add pool share in validator stake
- Check http://localhost:3000/stake-pools?network=testnet to see if new value is present (see comment in PT story)
- https://www.pivotaltracker.com/n/projects/2177859
> 180894658_add_pool_share_in_validator_stake

- app/views/public/api_documentation.html.erb
- Fix order and add missing lines in api docs
- Check the api docs and compare with the story description
- https://www.pivotaltracker.com/story/show/181012730
> 181012730_fix_order_in_api_docs

- app/views/public/api_documentation.html.erb
- test/controllers/api/v1/api_controller_test.rb
- Add vote_distance_history to api output
- Use postman and check API output if there is vote_distance_history for validator (`https://www.validators.app/api/v1/validators/:network.json/:account.json?with_history=true`)
- run tests
- https://www.pivotaltracker.com/story/show/181004431
> 181004431_api_endpoint_for_vote_distance_history

- app/controllers/api/v1/stake_accounts_controller.rb
- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/stake_account_row.js
- app/views/api/v1/stake_accounts/index.json.jbuilder
- test/controllers/api/v1/stake_accounts_controller_test.rb
- change epoch description
- add current epoch
- see the /stake-pools and check if current epoch is displayed correctly
- see if there's an explanation on the bottom
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180991266)
> 180991266-add-current-epoch-and-epoch-explanation

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/pool_stats.js
- As in title
- Review in the browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180992254)
> 180992254 Change naming for validators commission

- app/javascript/packs/stake_accounts/index_template.vue
- app/logic/stake_logic.rb
- app/models/stake_pool.rb
- test/logic/stake_logic_test.rb
- include manager_fee while calculating APY
- run tests
- test on stage
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180982503)
> 180982503 include pool fee

- app/javascript/packs/stake_accounts/pool_stats.js
- app/javascript/packs/stake_accounts/pools_overview.js
- app/views/stake_accounts/index.html.erb
- db/schema.rb
- doc/README-Apple-M1.md
> 20220126 nits

- app/javascript/packs/stake_accounts/stake_account_row.js
> 20220127 nits

- app/javascript/packs/stake_accounts/validator_row.js
- test/controllers/api/v1/api_controller_test.rb
- Admin warning visible for validators on stake pools
- check if it's there
- https://www.pivotaltracker.com/story/show/181051258
> 181051258-admin-warning-on-stake-pools

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/pools_overview.js
- Make stake pool name a link
Go to /stake-pools, find the section mentioned in PT story, click on new links, check if there are no console errors and if it works correctly
- https://www.pivotaltracker.com/story/show/181045280
> 181045280_add_link_to_single_pool_stat

- app/controllers/ping_things_controller.rb
- app/helpers/application_helper.rb
- app/views/ping_things/index.html.erb
- app/views/public/api_documentation.html.erb
- app/views/validators/_spark_line_chart.html.erb
- Views styling 
- see main branch for more details
> 181126039 ping thing view

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/stake_account_row.js
- Remove not used functions
- Check /stake-pools for console error and if works ok
- https://www.pivotaltracker.com/story/show/181187004
> 181187004_cleanup_vue_view

- app/javascript/packs/stake_accounts/index_template.vue
- package.json
- yarn.lock
- Add loadash library to set delay before sending request
- Go to /stake-pools
- Try to reproduce error from the story description
- It shouldn't happen
- https://www.pivotaltracker.com/story/show/181083586
> 181083586_search_does_not_work_correctly

- app/controllers/ping_things_controller.rb
- app/views/ping_things/_bubble_chart.html.erb
- app/views/ping_things/_scatter_chart.html.erb
- app/views/ping_things/index.html.erb
- Replaced default line chart with new scatter chart
- Generate some PingThings locally:
```
240.times do 
PingThing.create user_id: User.first.id, amount: 1, signature: "5zxrAiJcBkAHpDtY4d3hf8YVgKjENpjUUEYYYH2cCbRozo8BiyTe6c7WtBqp6Rw2bkz7b5Vxkbi9avR7BV9J1a6s", transaction_type: 'transfer', network: 'testnet', response_time: rand(200..400) 
end
```
- go to /ping-thing?network=testnet url in the browser and review the chart
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181206553) …
> 181206553 ping chart

- test/services/process_ping_things_service_test.rb
- fix invalid assertion
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181253646)
> 181253646-fix-tests-for-ping-thing

- app/javascript/packs/stake_accounts/pool_stats.js
- app/javascript/packs/stake_accounts/pools_overview.js
- Hotfix - hide APY for Lido until related issue (https://www.pivotaltracker.com/n/projects/2177859/stories/181280639) is resolved 
- Check /stake-pools in browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181280639)
> 181280639 Hide APY for Lido

- app/controllers/api/v1/ping_things_controller.rb
- app/models/ping_thing.rb
- app/models/user.rb
- app/views/public/api_documentation.html.erb
- config/routes.rb
- test/controllers/api/v1/ping_thing_controller_test.rb
- test/factories/ping_things.rb
- Adds ping things index endpoint to API
- See /api-documentation for example and test API
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181242138)
> 181242138 add ping thing list to api

- app/views/public/api_documentation.html.erb
- fix documentation for ping-thing-batch POST
- copy curl from the api example, add proper values and see if that works
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181327640)
> add } in curl for ping thing batches

- app/views/ping_things/_scatter_chart.html.erb
- app/views/ping_things/index.html.erb
- add delimiters in ping thing chart
- add ping things with different times and check if chart values looks good
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181249770)
> 181249770-separator-on-ping-thing-chart

- app/assets/stylesheets/tables.scss
- app/helpers/application_helper.rb
- app/helpers/ping_things_helper.rb
- app/views/ping_things/index.html.erb
- make application and commitment_level columns smaller
- Check if all columns on ping-thing page are displayed correctly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181310193)
> 181310193-reduce-ping-things-column

- app/views/ping_things/index.html.erb
- As in title
- Check in browser
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181357543)
> 181357543 Shorten ping signature

- app/logic/stake_logic.rb
- fix counting APY
- run tests
- after running script/gather_stake_accounts.rb all lido accounts should have nil apy (better test on staging)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181280639)
> 181280639 investigate apy error

- config/schedule.rb
- Use correct command to run new scripts
- Test on staging
- https://www.pivotaltracker.com/story/show/181204864
> 181204864_update_schedule_rb

- config/schedule.rb
- script/data_centers_scripts/append_data_centers_geo_data.rb
- script/migrate_from_ips_to_data_centers/copy_data_to_data_centers.rb
> 181204864_scritps_updates

- app/logic/solana_logic.rb
- app/models/validator.rb
- app/models/validator_ip.rb
- db/migrate/20220307163003_add_is_active_to_validator_ips.rb
- db/schema.rb
- script/concerns/NEW_fix_ip_module.rb
- script/data_centers_scripts/append_data_centers_geo_data.rb
- script/data_centers_scripts/assign_data_center_scores.rb
- script/data_centers_scripts/fix_data_centers_hetzner.rb
- script/data_centers_scripts/fix_data_centers_ovh.rb
- script/data_centers_scripts/fix_data_centers_webnx.rb
- script/one_time_scripts/set_is_active_in_validator_ips.rb
- test/factories/validator_ips.rb
- test/models/validator_ip_test.rb
- test/models/validator_test.rb
- add is active to validator ips
- migration + relationship + script to update validator_ips (need to be run manually)
- Run migration
- Run tests
- Run script `bundle exec rails r script/one_time_scripts/set_is_active_in_validator_ips.rb` and check if your validators got active validator_ip
- https://www.pivotaltracker.com/story/show/181482864
> 181482864_add_is_active_to_validator_ips

- app/models/validator_ip.rb
- Change update_all to update
- Run tests
- https://www.pivotaltracker.com/story/show/181482864
> 181482864_change_update_all_to_update

- config/schedule.rb
- Uncomment new scripts in schedule.rb
- Deploy to staging
- https://www.pivotaltracker.com/story/show/181525219
> 181525219_run_new_scripts_on_staging

- app/views/public/api_documentation.html.erb
- As in title
- Review in browser
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181569852)
> 181569852 fix typo in api docs

- app/models/validator.rb
- app/models/vote_account.rb
- order vote_accounts for api requests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181643340)
> 181643340-fix-vote-accounts-for-api

- app/views/devise/registrations/edit.html.erb
- app/views/layouts/_footer.html.erb
- app/views/you/index.html.erb
- Log in to your user account and check links in footer
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181283699)
> 181283699 add link to user account

- app/views/layouts/_footer.html.erb
- app/views/public/faq.en.html.erb
- Adds info to FAQ
- Review in browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181513756)
> 181513756 faq addition

- app/controllers/asns_controller.rb
- app/views/asns/show.html.erb
- Use only unique keys when displaying data centers
- Open ASN with duplicated data centers (in PT) there shouldn't be any now
- https://www.pivotaltracker.com/story/show/181570998
> 181570998_remove_duplicated_link

- app/controllers/validators_controller.rb
- Narrow results by using indexed created_at in where clause
- Click on the validators on index page, check how long they are loaded
- https://www.pivotaltracker.com/story/show/181583636
> 181583636_investigate_performance_on_show_page

- app/controllers/api/v1/sol_prices_controller.rb
- Fix failing test (see PT story)
- Run tests
- https://www.pivotaltracker.com/story/show/181570574
> 181570574_fix_failing_test

- config/routes.rb
- Use dash instead of underscore in route name for sol prices
- Run tests 
- Open sol_prices from bottom menu
- https://www.pivotaltracker.com/story/show/181727053
> 181727053_unify_routes

- app/controllers/api/v1/validators_controller.rb
- app/controllers/concerns/validators_controller_helper.rb
- app/models/validator_score_v1.rb
- test/controllers/api/v1/validators_controller_test.rb
- Correctly set with_history param
- Run tests
- Send request for single validator with different values of `with_history` param
- https://www.pivotaltracker.com/story/show/181570115
> 181570115_with_history_option

- script/data_centers_scripts/append_data_centers_geo_data.rb
- Use custom max mind client
- Run `rails r script/data_centers_scripts/append_data_centers_geo_data.rb` it should works the same as before
- https://www.pivotaltracker.com/story/show/181679704
> 181679704_use_maxmind_in_logic

- daemons/gather_rpc_mainnet_daemon.rb
- daemons/gather_rpc_testnet_daemon.rb
- dev/report_tower_height.rb
- script/gather_rpc_data.rb
- script/gather_rpc_data_mainnet.rb
- test/logic/report_logic_test.rb
- Use stringify_keys on hashes sent to sidekiq workers
- Run tests
- Check if everything works fine on staging
- https://www.pivotaltracker.com/story/show/181770137
> 181770137_fix_warning

- app/controllers/vote_accounts_controller.rb
- app/views/vote_accounts/_vote_account_histories_table.html.erb
- Use created_at from index to speed up the query
- Check vote accounts show page, it should have no slow query now
- https://www.pivotaltracker.com/story/show/181846395
> 181846395_investigate_slow_query_on_vote_account

- app/controllers/asns_controller.rb
- app/controllers/vote_accounts_controller.rb
- as in title
- go to a vote account that does not exist and see if 404 page is displayed correctly
> add layout: nil in 404

- app/controllers/vote_accounts_controller.rb
- app/views/validators/show.html.erb
- config/routes.rb
- test/controllers/vote_accounts_controller_test.rb
- Use last vote_account
- Check the vote account from PT story
- https://www.pivotaltracker.com/story/show/181846381
> 181846381_fix_displayed_validator_identity

- app/controllers/api/v1/validators_controller.rb
- app/queries/validator_query.rb
- test/queries/validator_query_test.rb
- Use query from ValidatorQuery in show page as well
- Get single validator info from api endpoint, it should works as previously
- https://www.pivotaltracker.com/story/show/181583347
> 181583347_unify_query_for_list_and_single_validator

- config/deploy.rb
- Fix crontab update
- cap production deploy
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181907910)
> 181907910 fix whenever capistrano config

- Gemfile
- Gemfile.lock
- config/deploy.rb
- Fix sidekiq not being restarted after deploy 
- cap stage deploy
- systemctl --user status sidekiq.service
-[ URL to the PivotalTracker ticket
](https://www.pivotaltracker.com/n/projects/2177859/stories/181907853)
> 181907853 fix sidekiq capistrano

- app/services/validator_check_active_service.rb
- test/services/validator_check_active_service_test.rb
- Create separate condition
- Run tests
- https://www.pivotaltracker.com/story/show/181958427
> 181958427_fix_conditions

- app/controllers/api/v1/ping_thing_stats_controller.rb
- app/models/ping_thing_stat.rb
- app/services/create_ping_thing_stats_service.rb
- app/views/public/api_documentation.html.erb
- test/controllers/api/v1/ping_thing_stats_controller_test.rb
- test/controllers/api/v1/ping_things_controller_test.rb
- test/models/ping_thing_stat_test.rb
- test/services/create_ping_thing_stats_service_test.rb
- add ping thing stats to api
- Run request from curl or postman
- Run tests
- https://www.pivotaltracker.com/story/show/181886696
> 181886696_add_ping_thing_stats_to_api

- .github/workflows/pronto.yml
- .github/workflows/test_suite.yml
- Update actions
- Check gh actions run
- https://www.pivotaltracker.com/story/show/181967839
> 181967839_update_gh_actions

- app/services/gatherers/vote_account_details_service.rb
- Add log file to script 
- Run rails r daemons/gather_vote_account_details_daemon.rb 
- https://www.pivotaltracker.com/story/show/182010781
> 182010781_reset_vote_authority_warning

- app/models/validator.rb
- dev/remove_devnet_validators.rb
- Delete validators from devnet
- fix total stake in software versions report
- check if everything that should be deleted for those validators are really deleted (best to test on staging)
- check if numbers on software version report are correct
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182137900)
> 182137900 fix software versions reports

- app/services/sorted_data_centers.rb
- app/views/data_centers/_asn_head.html.erb
- app/views/data_centers/_asn_list.html.erb
- app/views/data_centers/_data_center_head.html.erb
- app/views/data_centers/_data_center_list.html.erb
- app/views/data_centers/data_center.html.erb
- app/views/data_centers/index.html.erb
- config/locales/en.yml
- Add active_stake_from_active_validators
- Run tests
- Check data_centers total stake (see comments in PT story)
- https://www.pivotaltracker.com/story/show/182138085
> 182138085_check_active_value

- app/models/vote_account.rb
- app/services/gatherers/vote_account_details_service.rb
- db/schema.rb
- the vote account script should set the correct is_active flag if there is no expected response from solana
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182283420)
> 182283420-fix-vote_account_details_service

- app/views/public/faq.en.html.erb
- A in title
- Review Getting Started page in the browser (http://localhost:3000/faq)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182289620)
> 182289620 add missing info to scoring description

- app/javascript/packs/stake_accounts/validator_row.js
- app/views/public/faq.en.html.erb
- app/views/validators/_scores.html.erb
- rename security report score to bonus point
- make sure the name has been changed in all places
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182302569)
> security report -> bonus point

- app/views/validators/index.html.erb
- Shows scored_at instead of created_at date on homepage
- Review on homepage
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182325116)
> Show scored_at date in batch

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/tables.scss
- app/javascript/src/watch_buttons.js
- app/views/public/faq.en.html.erb
- app/views/validators/_table.html.erb
- app/views/validators/index.html.erb
- config/locales/en.yml
- Updates views
- Review in the browser
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182235395)
-[ URL to the PivotaTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182332125)
> 182332125 Watchlist styling

- app/controllers/public_controller.rb
- app/controllers/validators_controller.rb
- app/views/cluster_stats/index.html.erb
- app/views/validators/show.html.erb
- config/routes.rb
- test/controllers/validators_controller_test.rb
- remove public#index since it duplicates validators#index
- check if links to home page are working correctly
- check if home page is working as it should
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182343411)
> 182343411-remove-public-index

- app/logic/asn_logic.rb
- app/models/validator.rb
- app/models/validator_score_v1.rb
- app/queries/commission_history_query.rb
- app/queries/validator_search_query.rb
- app/services/data_centers/change_validator_data_center.rb
- script/concerns/fix_data_center_module.rb
- script/data_centers_scripts/append_data_centers_geo_data.rb
- script/data_centers_scripts/assign_data_center_scores.rb
- script/data_centers_scripts/fix_data_centers_hetzner.rb
- script/data_centers_scripts/fix_data_centers_ovh.rb
- script/data_centers_scripts/fix_data_centers_webnx.rb
- test/controllers/api/v1/validators_controller_test.rb
- test/factories/validator_score_v1s.rb
- test/logic/asn_logic_test.rb
- test/models/validator_ip_test.rb
- test/models/validator_score_v1_test.rb
- test/queries/commission_history_query_test.rb
- test/queries/stake_account_query_test.rb
- test/queries/validator_search_query_test.rb
- test/services/data_centers/change_validator_data_center_test.rb
- test/services/sorted_data_centers_test.rb
- USe data_center_key from data_centers
- Run tests
- Search for validators by data_center_key
- Run this branch on staging, check results after one day
- https://www.pivotaltracker.com/story/show/182194044
> 182194044_remove_data_center_key_from_score

- app/models/user.rb
- test/models/user_test.rb
- Accept longer domain names in emails
- Run tests
- https://www.pivotaltracker.com/story/show/182415038
> 182415038_fix_email_regexp

- app/services/object_copy_service.rb
- confirm users created by copy feature
- create new user and ping thing with the user
- check if user copied to other db is confirmed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182426083)
> confirm user

- app/assets/stylesheets/typography.scss
- app/controllers/api/v1/ping_things_controller.rb
- app/javascript/packs/ping_thing/index_template.vue
- dev/create_test_ping_things.rb
- test/controllers/api/v1/ping_things_controller_test.rb
- tweaks 5-min charts layout
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859)
> 182473504 p90 ping thing stat appearance

- app/javascript/packs/ping_thing/ping_thing_header.vue
- app/views/validators/_banner.html.erb
- Updates copy
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182558528)
> 182558528 change copy

- .gitignore
- README.md
- db/seeds.rb
- script/add_current_epoch.rb
- simple seed update
- check the instructions.md file in keybase
- run `rails db:seed`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182522755)
> 182522755-dev-instructions

- app/javascript/packs/ping_thing/index_template.vue
- Combine stats into single element
- See the ping things, 5 min and 60 min stats should be in one card now
- https://www.pivotaltracker.com/story/show/182648080
> 182648080_combine_stats_into_single_element

- app/views/validators/_table.html.erb
- Remove sequence number from validators listing
- See the index page, there should be no sequence numbers.
- https://www.pivotaltracker.com/story/show/182648033
> 182648033_drop_sequence_number

- app/views/validators/_scores.html.erb
- Add validator name to score card
- Check score card, you should see validator name on
- https://www.pivotaltracker.com/story/show/182653536
> 182653536_add_validator_name_in_the_score_card

- app/assets/stylesheets/application.scss
- app/javascript/packs/ping_thing/index_template.vue
- Add header to stats
- https://www.pivotaltracker.com/story/show/182653482
> 182653482_add_header_to_ping_thing_stats

- app/models/validator_score_v1.rb
- db/migrate/20220712063024_add_index_to_validator_score_v1.rb
- db/schema.rb
- add indexes to validator_score_v1
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182695680)
> 182695680-fix-missing-indexes

- app/views/layouts/application.html.erb
- ensure that js is working correctly after going backwards in browser
- check examples included in the story
- try multiple browsers
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182634801)
> 182634801-reload-js-on-backwards

- app/views/layouts/application.html.erb
- app/views/validators/index.html.erb
> disable turbolinks only on root page

- app/queries/validator_query.rb
- config/environments/test.rb
- search by query only when query is present + remove unnecessary includes
- https://www.pivotaltracker.com/story/show/182663236
> 182663236_investigate_long_time_loading

- app/controllers/concerns/validators_controller_helper.rb
- app/models/validator.rb
- app/models/validator_score_v1.rb
- app/queries/validator_query.rb
- test/models/validator_test.rb
- test/queries/validator_query_test.rb
- Use only needed fields in web requests
- Check main page and api - there shoud be no differences in data returned ant the times should be slightly better
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182663236)
> 182663236_load_only_needed_fields

- app/views/validators/_banner.html.erb
Removes the H2 line and adds a link to unstake.it
> Removes the H2 line and adds a link to unstake.it

- app/views/validators/_banner.html.erb
- app/views/validators/show.html.erb
- Breaks too long text, eg. https://www.validators.app/validators/C1ocKDYMCm2ooWptMMnpd5VEB2Nx4UMJgRuYofysyzcA?locale=en&network=mainnet
- Confirm that words longer than container are broken, other words remain unchanged
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182745396)
> 182745396 wrap long text

- script/data_centers_scripts/fix_data_centers_webnx.rb
- check title
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182558094)
> add nyc to webnx script

- app/views/validators/show.html.erb
- Adds "inactive" label to validator show view
- 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182790703)
> 182790703 Add inactive label

- config/schedule.rb
- update schedule.rb to avoid various scripts running at the same time
- check if there's anything missing in schedule.rb file
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182772075)
> 182772075-spread-out-scheduled-tasks

- app/channels/ping_thing_recent_stat_channel.rb
- app/controllers/api/v1/ping_thing_recent_stats_controller.rb
- app/controllers/api/v1/ping_things_controller.rb
- app/javascript/packs/ping_thing/index_template.vue
- app/javascript/packs/ping_thing/stats_bar.vue
- app/models/ping_thing_recent_stat.rb
- config/routes.rb
- test/channels/ping_thing_recent_stats_channel_test.rb
- test/controllers/api/v1/ping_thing_recent_stats_controller_test.rb
- test/controllers/api/v1/ping_things_controller_test.rb
- top stats bar in Ping Things should be updated with ActionCable
- open ping things and update PingThingRecentStat - changes should be applied
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182527512)
> 182527512 live update top stats bar

- app/api_clients/max_mind_client.rb
- Add rescuing when insufficient fund error occurs
- Run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182746725)
> 182746725_send_info_when_maxmind_returns_insufficient_funds

- app/services/validator_check_active_service.rb
Reverts brianlong/www.validators.app#507
https://www.pivotaltracker.com/n/projects/2177859/stories/182866586
> Revert "182619709_review_deactivation_script"

- app/services/validator_check_active_service.rb
- Check if validator has validator histories 
- Deploy to production
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182619709)
> 182619709_deactivation_script

- script/data_centers_scripts/append_data_centers_geo_data.rb
- Reject only private ips when assigning data center
- Check regexp against some IPs in rubular
- Check in rails console
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182816507)
> 182816507_fix_validator_ip_private_pattern

- app/models/validator_score_v1.rb
- db/migrate/20220715085454_remove_indexes_from_validator_score_v1.rb
- db/schema.rb
- 182708197-remove-unnecessary-score-indexes
- run migration and check if there's no errors
- try the rollback
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182708197)
> remove single column indexes

- script/data_centers_scripts/append_data_centers_geo_data.rb
- Remove assigning data_center_key to validator_score_v1 
- Run script locally (on staging it works every hour)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182817958)
> 182817958_remove_assigning_data_center_key_to_score

- app/controllers/asns_controller.rb
- app/controllers/data_centers_controller.rb
- app/models/validator_score_v1.rb
- test/models/validator_score_v1_test.rb
- Fix counting total stake
- See the numbers after change - active stake percentage numbers should be the same in index and in show page for data_centers and asns
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182805514)
> 182805514_fix_displaying_total_stake_percentage

- dev/remove_devnet_validators.rb
- update script removing validators to get validator data from args
- try to remove any validator with the script (rails r dev/remove_devnet_validators.rb <network> <account>)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182783470)
> 182783470-update-devnet-validators-script

- app/models/user.rb
- test/models/user_test.rb
- Allow duplicate email addresses
> Allow duplicate email addresses

- app/javascript/packs/ping_thing/stats_bar.vue
- app/views/validators/_banner.html.erb
- add link to ping thing on pt stats card on home page
- check if the link is displayed only on home page and works properly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182954642)
> 182954642-link-to-ping-thing-stats-on-home-page

- app/controllers/vote_accounts_controller.rb
- Use network to find correct validator
- See the validator from PT, vote account should be displayed correctly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183002551)
> 183002551_investigate_vote_account

- script/concerns/fix_data_center_module.rb
- script/data_centers_scripts/fix_data_centers_hetzner.rb
- script/data_centers_scripts/fix_data_centers_ovh.rb
- script/data_centers_scripts/fix_data_centers_webnx.rb
- Change module name
- Run scripts locally or on staging, should work as previously
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183012482)
> 183012482_fix_module_name

- app/controllers/asns_controller.rb
- app/controllers/cluster_stats_controller.rb
- app/controllers/data_centers_controller.rb
- app/models/asn_stat.rb
- app/models/batch.rb
- app/models/data_center.rb
- app/models/validator.rb
- app/models/validator_block_history.rb
- app/models/validator_ip.rb
- app/models/validator_score_v1.rb
- app/models/vote_account.rb
- app/queries/validator_query.rb
- db/migrate/20220826104458_add_traits_autonomous_system_number_index_to_data_centers.rb
- db/migrate/20220826113209_update_network_active_stake_index_in_validator_score_v1s.rb
- db/migrate/20220826133743_update_index_in_validators.rb
- db/migrate/20220826141204_update_index_in_data_centers.rb
- db/migrate/20220826144138_add_index_on_network_to_asn_stats.rb
- db/migrate/20220826145420_remove_validator_id_index_from_validator_block_histories.rb
- db/migrate/20220829103939_remove_single_validator_id_index_from_vote_accounts.rb
- db/migrate/20220829131601_remove_single_validator_id_index_on_validator_ips.rb
- db/migrate/20220831134326_remove_network_index_on_batches.rb
- db/schema.rb
- review queries in front
- Run migrations
- Click through website
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182772158)
> 182772158_review_queries_in_front

- app/assets/stylesheets/header.scss
- Fix focus state colour
- Turn on forced focus in browser console
- Tracker 183154857
> 183154857 Add focus state for nav-link in css

- app/helpers/email_helper.rb
- app/mailers/application_mailer.rb
- app/mailers/commission_history_mailer.rb
- app/services/create_commission_history_service.rb
- app/views/commission_history_mailer/commission_change_info.html.erb
- app/views/commission_history_mailer/commission_change_info.text.erb
- app/views/devise/shared/_side_banner.html.erb
- app/views/public/faq.en.html.erb
- test/mailers/commission_history_mailer_test.rb
- test/mailers/previews/commission_history_mailer_preview.rb
- test/services/create_commission_history_service_test.rb
- send email about commission changes to interested users
- run tests
- add some validator to favorites 
- see the email here `http://localhost:3000/rails/mailers/commission_history_mailer/commission_change_info`
- try running in console `CreateCommissionHistoryService.new(score).call` (where score is the scorev1 of the validator added to favorites) and see if there's an email displayed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183240688)
> 183240688 email about commission changes

- app/controllers/api/v1/ping_things_controller.rb
- app/javascript/packs/ping_thing/ping_thing_table.vue
- app/models/ping_thing.rb
- app/models/ping_thing_raw.rb
- app/views/public/api_documentation.html.erb
- db/migrate/20220916065710_add_slot_fields_to_ping_things.rb
- db/schema.rb
- test/controllers/api/v1/ping_things_controller_test.rb
- test/factories/ping_things.rb
- add slot_sent and slot_landed to ping things
- run migration
- run tests
- try adding ping things with new fields through API POST (both single and batch should work)
- check if API GET returns those fields
- check if views are displayed correctly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183281707)
> 183281707 add slot fields to ping things

- app/services/data_centers/merge_duplicates.rb
- app/services/data_centers/remove_without_validators_and_gossip_nodes.rb
- update script for merging and removing duplicates
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183313957)
> 183313957_update_script_for_merging_duplicates

- app/views/public/commission_histories.html.erb
- app/views/validators/_watchlist_info_banner.html.erb
- app/views/validators/index.html.erb
- adds some info about watchlist with links to sign up page
- Review in browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183276745)
> 183276745 info about features for registered users

- app/services/data_centers/check_ip_info_service.rb
- config/schedule.rb
- script/data_centers_scripts/append_data_centers_geo_data.rb
- script/data_centers_scripts/check_unknown_data_centers_for_updates.rb
- once a day run through maxmind client validator_ips from unknown data center.
- tested on stage (There had to be some validators on unknown data center)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183287070)
> 183287070 check validators from unknown data centers

- app/models/gossip_node.rb
- test/models/gossip_node_test.rb
- Add validator_ip_active relationshipto gossip_node model
- Run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183341305)
> 183341305_add_validator_ip_activeTo_gossip_nodes

- lib/tasks/add_stake_pools.rake
PR applies the updates for stake pool fees.
> 183331921 - update the fees for stake pools

- app/javascript/packs/ping_thing/ping_thing_table.vue
- app/services/create_ping_thing_stats_service.rb
- slot latency should show "( - )" if there's no slot_sent or slot_landed
- see the /ping-things page 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183340126)
> 183340126 fix slot latency display

- app/services/validator_ips/remove_duplicated_inactive_validator_ips.rb
- script/validator_ips/remove_duplicated_inactive_validator_ips.rb
- Add service and script to remove duplicated validators_ips
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183341356)
> 183341356_remove_duplicated_inactive_validator_ips

- app/models/gossip_node.rb
- test/models/gossip_node_test.rb
- Create validator ip as active for gossip nodes
- Run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183390859)
> 183390859_create_active_validator_ips_for_gossip_nodes

- config/environments/development.rb
- config/routes.rb
- test/mailers/previews/commission_history_mailer_preview.rb
- Add lette_opener
-  Visit localhost:3000/letter_opener
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183274925)
> 183274925_add_letter_opener

- app/views/validators/_table.html.erb
- Check max chart value position for vote distance chart; should be now placed in the right position
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183370357)
> 183370357 Chart annotations hotfix (typo)

- app/logic/gossip_node_logic.rb
- app/models/data_center_host.rb
- app/models/gossip_node.rb
- test/models/data_center_host_test.rb
- test/models/data_center_test.rb
- test/models/gossip_node_test.rb
- Use validator ip active
- Run tests
- Check on staging
- Check the api results for gossip nodes
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183379638)
> 183379638_use_validator_ip_active_on_gossip_nodes

- .browserslistrc
- package.json
- yarn.lock
Add web3 package and fix the browserlist config.
- URL to the [PivotalTracker](https://www.pivotaltracker.com/story/show/183402909) ticket
> 183402909- Add web3 solana package; fix browserlist config

- app/channels/sol_price_channel.rb
- app/javascript/packs/sol_prices/sol_price_component.js
- app/javascript/packs/sol_prices/sol_price_component_template.vue
- app/views/validators/index.html.erb
- config/webpack/loaders/vue.js
- daemons/front_stats_update.service
- daemons/front_stats_update_daemon.rb
- package.json
- yarn.lock
- create component displaying solana price
- run `rails r daemons/front_stats_update_daemon.rb`
- check component on landing page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183408173)
> 183408173-sol-prices-live

- app/javascript/packs/transactions/transactions_stats_component.js
- app/javascript/packs/transactions/transactions_stats_component_template.vue
- app/views/validators/index.html.erb
- component with solana transactions statistics
- see the component on front page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183408246)
> 183408246-tx-stats-component

- app/javascript/packs/epoch/epoch_stats_component.js
- app/javascript/packs/epoch/epoch_stats_component_template.vue
- app/views/validators/index.html.erb
- add Epoch stats component on home page
- visit home page and check i component displays data correctly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183408215)
> epoch stats

- app/javascript/packs/validators/circulating_supply.js
- app/javascript/packs/validators/circulating_supply.vue
- app/views/validators/_stake_stats_banner.html.erb
- app/views/validators/home_new.html.erb
PR adds the circulating supply card.
Verify the circulating supply data at the homepage.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183523163)
> 183523163 - add circulating supply component to the homepage

- app/javascript/packs/validators/circulating_supply.vue
> 183531771 - fix circulating supply delay

- app/javascript/packs/epoch/epoch_stats_component.js
- app/javascript/packs/epoch/epoch_stats_component_template.vue
- app/javascript/packs/stores/main_store.js
- app/javascript/packs/transactions/transactions_stats_component.js
- app/javascript/packs/transactions/transactions_stats_component_template.vue
- app/javascript/packs/validators/circulating_supply.js
- app/javascript/packs/validators/circulating_supply.vue
- package.json
- yarn.lock
- add vuex with web3 url
- check if components on the new front page are working as expected
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183524092)
> 183524092 web3 url

- package.json
- yarn.lock
PR bumps the Vuex.
Should be tested on stage and should be looking for any warnings or errors in vuex components.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183556164)
> Bump Vuex to 3.6.2

- app/views/validators/_ping_stats_banner.html.erb
- app/views/validators/index.html.erb
- Ping This stats component is not displayed on homepage correctly. This little hotfix fixes it.
> Fix ping thing stats on homepage

- app/assets/stylesheets/map.scss
- app/javascript/packs/validators/validators_map_data_center_details.js
- app/views/validators/home_new.html.erb
- Updates new homepage layout and styling
- Go to the /home-new url, review the page,  click on map bubbles
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183580511)
> 183580511 update new homepage layout

- app/javascript/packs/leaders/leaders_stats_component_template.vue
- app/views/validators/home_new.html.erb
- As in title - tweaks an issue visible on the screenshot attached to PT story
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183607656)
> 183607656 tweak homepage layout on mobiles

- app/logic/agent_logic.rb
- script/validators_update_avatar_url.rb
PR fixes the validator avatar update daemon.
Need to run the daemon - `script/validators_update_avatar_url.rb`
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183567669)
> 183567669 - fix missing method error; daemon minor improvements

- app/javascript/packs/leaders/leaders_stats_component.js
- app/javascript/packs/leaders/leaders_stats_component_template.vue
- app/javascript/packs/validators/validators_map.js
- app/javascript/packs/validators/validators_map.vue
PR adds testnet network access for Leader and Validators Map component.
Compare stats in homepage for testnet / mainnet.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183591385)
> 183591385 - fix missing testnet leader and validators map

- app/controllers/sol_prices_controller.rb
- do not cause 500 when there's no average_price for coin_gecko
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183615143)
> 183615143 search sol_prices with average_price

- app/controllers/api/v1/ping_things_controller.rb
- app/javascript/packs/ping_thing/index_template.vue
- app/javascript/packs/ping_thing/ping_thing_table.vue
- test/controllers/api/v1/ping_things_controller_test.rb
- filter ping thing table based on the minimum time 
- run dev/create_test_ping_things.rb to populate ping things
- run tests
- check http://localhost:3000/ping-thing and see if the filter works as expected
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183383678)
> 183383678 Search for ping things

- app/javascript/packs/leaders/leaders_stats_component_template.vue
- Adds links to leader component
- Run `rails r daemons/front_stats_update_daemon.rb`
- Go to /home-new and click on validator name and avatar. Confirm that correct page is opened.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183580265)
> 183580265 add link to validator details

- config/deploy.rb
Turn on leader daemon task upon the restart.
PR should be tested on stage. Check if leader component updates successfully.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183651877)
> 183651877 - uncomment leader stats update daemon during restart task

- app/views/validators/_table.html.erb
- As in title description
- Go to ANS details view
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183699520)
> 183699520 Display software version on ASN view

- script/data_centers_scripts/check_hetzner_admin_warning.rb
> add environment to script

- app/controllers/data_centers_controller.rb
PR reduces time to load the data center details page.
Check whether the development shows any eager loading errors. You can compare the rendering time being on that branch and the master.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183153035)
> 183153035 - reduce data center details loading time

- app/helpers/validators_helper.rb
- app/javascript/packs/software_versions/software_versions_template.vue
- daemons/concerns/front_software_versions_module.rb
> 183734690-fix-software-versions-for-testnet

- app/assets/stylesheets/map.scss
- app/javascript/packs/validators/validators_map.js
- app/javascript/packs/validators/validators_map.vue
- daemons/concerns/front_stats_constants.rb
- daemons/concerns/leader_stats_helper.rb
- test/daemons/leader_stats_helper_test.rb
- show location of a leader on a home page map
- check the map on all the networks. there should be an avatar of the leader displayed and changing along with the leader change
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183408323)
> 183408323 integrate current leader with map

- app/models/ping_thing.rb
- app/models/ping_thing_recent_stat.rb
- app/models/ping_thing_stat.rb
- app/models/stats/validator_block_history.rb
- app/models/stats/validator_history.rb
- app/models/stats/validator_score.rb
- app/models/stats/vote_account_history.rb
- Update network in models
- Try to create PingThing object with `pythnet` network
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730447)
> 183730447-update network in models

- app/api_clients/coin_gecko_client.rb
- app/javascript/packs/sol_prices/sol_price_component_template.vue
- daemons/front_stats_update_daemon.rb
- test/api_clients/coin_gecko_client_test.rb
- test/vcr_cassettes/api_clients/coin_gecko_client_test/test__price.yml
- as in title
- check if the prices on home page are working correctly 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183791066)
> 183791066 coin gecko instead of ftx on home

- config/routes.rb
- config/validator_blacklist.yml
As in the title.
You can run the following in the console:
`Rails.application.config.validator_blacklist`
and check for pythnet presence.
Also, check if the `rails routes` returns for pythnet entries.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730541)
> 183730541 - add pythnet to config and routes

- app/javascript/packs/validators/validators_map.vue
> 183794034-rpc-nodes-off-by-default

- app/workers/ping_thing_stats_worker.rb
- Update networks in workers
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730534)
> Use NETWORKS constant in workers

- config/schedule.rb
PR adds pythnet cronjobs.
To test changes you can manually run the pythnet workers included in schedule.rb file.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730432)
> 183730432 - add pythnet cronjobs

- app/javascript/packs/ping_things/stats_chart.js
- app/models/ping_thing_stat.rb
- dev/create_test_ping_things.rb
- script/one_time_scripts/back_fill_ping_thing_stats.rb
- test/services/create_ping_thing_stats_service_test.rb
- add 7 day chart for ping things
- run `rails r dev/create_test_ping_things.rb`
- run `rails r script/one_time_scripts/back_fill_ping_thing_stats.rb`
- see the chart on `http://localhost:3000/ping-thing?locale=en&network=mainnet`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183801739)
> 183801739-7-day-ping-thing-chart

- app/services/solana_rpc_client.rb
- daemons/concerns/leader_stats_helper.rb
- script/add_current_epoch.rb
- script/gather_stake_accounts.rb
- script/one_time_scripts/back_fill_commission_history.rb
- script/one_time_scripts/back_fill_epoch_data.rb
- script/one_time_scripts/back_fill_ping_thing_stats.rb
- script/one_time_scripts/reduce_validators_with_invalid_config.rb
- script/update_gossip_nodes.rb
- script/validators_get_avatar_url.rb
- script/validators_get_info.rb
- script/validators_update_avatar_url.rb
- test/scripts/add_current_epoch_script_test.rb
- test/services/solana_rpc_client_test.rb
- Add pythnet to scripts
- run `rails r script/add_current_epoch.rb`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730467)
> 183730467 - add pythnet to scripts

- app/views/public/api_documentation.html.erb
PR adds pythnet network to api documentation.
Check /api-documentation page.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730472)
> 183730472 - add pythnet to controllers

- lib/tasks/add_stake_pools.rake
Change deposit fee value to 0.
`rails add_stake_pool:mainnet`
`rails update_fee_in_stake_pools:mainnet`
Check https://jito-foundation.gitbook.io/jitosol/faqs/general-faqs#fees for fees information and compare it with the ones that we included in stake pools page.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183861609)
> 183861609 - setting up 0 value for deposti fee for Jito

- db/seeds.rb
- script/add_current_epoch.rb
PR removes useless network variable placed in seeds.
Run `rails db:seed` and check for errors.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730545)
> 183730545 - update seeds with pythnet

- app/helpers/validators_helper.rb
PR adds pythnet to helpers.
Changes apply to leader component and cluster stat helper.
- check leader component at homepage
- also check the cluster stat page for any errors.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730501)
> 183730501 - update helpers with pythnet

- config/deploy.rb
- As indicated in PR title
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183814668)
> 183814668 Uncomment restart tasks

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/header.scss
- app/javascript/packs/navigations/network_buttons.js
- app/javascript/packs/navigations/network_buttons_template.vue
- app/javascript/packs/stores/main_store.js
- create dropdown instead of toggle and include pythnet
- check if dropdown has pythnet and switches networks as it should
- check design for mobile
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730407)
> 183730407 network select

- app/helpers/validators_helper.rb
- app/javascript/packs/stores/main_store.js
- config/initializers/cluster.rb
- daemons/front_stats_update_daemon.rb
- prepare home page to work with pythnet
- check if all of the components work correctly with pythnet
> add pythnet to cluster stats and link for web3

- daemons/concerns/front_software_versions_module.rb
- daemons/concerns/front_stats_constants.rb
- daemons/front_stats_update_daemon.rb
PR adds pythnet to front stats daemon and hereby it fixes the software versions component.
- 'rails r daemons/front_stats_update_daemon.rb`
- verify software versions at homepage for pythnet network
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183888684)
> 183888684 - fix pythnet software version

- lib/tasks/add_stake_pools.rake
- as in title
-  `rails update_fee_in_stake_pools:mainnet`
- check if blazestake was updated
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183892427)
> 183892427-update-blazestake-fees

- app/helpers/validators_helper.rb
- app/views/validators/show.html.erb
Adds delegate on BlazeStake button in validator detail page.
Verify the validator details page in terms of the new BlazeStake button presence. Check if it redirects to valid address.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183888131)
> 183888131 - add button for BlazeStake

- app/views/public/home.html.erb
- app/views/validators/_watchlist_info_banner.html.erb
- As in PR title, hides sol prices and stake pools cards if network is pythnet
- Go to homepage, switch networks
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183909574)
> 183909574 hide cards for pythnet

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/images.scss
- Fixes the issue with private avatars described in PT
- Log in 
- Go to validators index, and sort validators by stake to see some private ones at the top of the list
- Confirm that the star-shaped icon next private avatars is now displayed correctly (compare to the screenshot attached to PT story)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183891269)
> 183891269 fix broken icon

- config/deploy.rb
- Uncomments new deploy tasks
- Deploy to staging and confirm there are no errors
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183888486)
> Uncomment deploy tasks

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/header.scss
- app/javascript/packs/ping_things/stats_bar.vue
- app/views/public/home.html.erb
- Go to the homepage and confirm that it contains h1 heading
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183957695)
> 183957695 Add heading to homepage

- app/mailers/contact_request_mailer.rb
- app/views/opt_out_requests/thank_you.erb
- config/initializers/site_information.rb
- Adds Brian to opt out notifiations
- Go to http://localhost:3000/opt-out-requests/new and fill the form
- Go to localhost:3000/letter_opener and confirm that Brian's email address is present
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183999690)
> 183999690 add brian to opt out messages

- app/models/sol_price.rb
- app/services/sol_prices/parsers/coin_gecko.rb
- app/views/public/api_documentation.html.erb
- db/migrate/20221220130340_remove_ftx_attributes_from_sol_price.rb
- db/schema.rb
- test/logic/sol_prices/shared_logic_test.rb
PR removes ftx attributes.
- rails test
- check the sol price model if ftx attributes are presented
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184045242)
> 184045242 - remove ftx attributes from sol price

- .github/workflows/pronto.yml
> 184150930-fix-gh-pronto

- app/javascript/packs/validators/components/block_history_chart.js
- app/javascript/packs/validators/components/skipped_slots_chart.js
- app/javascript/packs/validators/components/vote_history_chart.js
- app/javascript/packs/validators/validator_details.js
- app/javascript/packs/validators/validator_details.vue
- Updates validators charts syntax
- Run pipelines (rpc gather and score pipelines) so that they create at least 2 batches, remember to run sidekiq
- Go to any active validator and compare the charts against production
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184193352)
> 184193352 tweak validator details charts

- app/javascript/packs/validators/validator_details.vue
- Fixes a link to vote account details page
- Go to validator, click on the link to vote account
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184196346)
> 184196346 fix link to vote account

- app/javascript/packs/validators/validator_details.vue
- Fixes some parts of HTML structure and styling on validator details page
- Compare the buttons alignment against production
- some good examples to compare top buttons:
https://stage.validators.app/validators/GJWNvD79Rcg6xLR2kKmEBNzMZAJxyTTh5uEUsQytaucL?locale=en&network=mainnet&order=&refresh=
&
https://stage.validators.app/validators/ateamuvZX4iy2xYrNrMyGgwtTpWFiurNzHpmJMZwjar?locale=en&network=mainnet&page=96
- 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184205113)
> 184205113 fix styling

- app/javascript/packs/validators/validator_details.vue
- Fixes a link to security report
- Test on some validator that has security report, eg. 7MTjmteQHhthwwTZhUzsc2dP4NBvGNRqj8jzdqNxHFGE
- https://stage.validators.app/validators/7MTjmteQHhthwwTZhUzsc2dP4NBvGNRqj8jzdqNxHFGE?locale=en&network=mainnet
- https://stage.validators.app/validators/DDnAqxJVFo2GVTujibHt5cjevHMSE9bo8HJaydHoshdp?locale=en&network=mainnet
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184214229)
> 184214229 fix link to security report

- app/logic/gossip_node_logic.rb
- app/logic/solana_logic.rb
- app/logic/solana_requests_logic.rb
- app/logic/stake_logic.rb
- app/services/gatherers/vote_account_details_service.rb
- test/logic/solana_logic_test.rb
- test/logic/solana_request_logic_test.rb
PR moves logic regarding Solana requests in to separated module.
- `rails test`
- manually check some daemons which are benefiting from SolanaLogic module (e. g. `daemons/gather_rpc_mainnet_daemon.rb`) for any suspicious issues.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184246339)
> 184246339 - create SolanaRequestLogic module

- app/models/epoch_wall_clock.rb
- app/services/track_commission_changes_service.rb
- test/services/track_commission_changes_service_test.rb
- fix track commission changes service to process only active vote accounts
- run tests
- check on stage
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184339573)
> 184339573-fix-commission-changes-script

- app/javascript/packs/validators/validators_map.vue
- Run the server, click on the link
- Confirm that the network is correctly passed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184363047)
> 184363047 Add link to data centers on homepage

- app/views/data_centers/index.html.erb
- Go to data centers page and see the count on top
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184363018)
> 184363018 Add DC/ASN count to data centers view

- app/queries/commission_history_query.rb
- On commission changes view, we now show all comission changes, not only for active validators (see `scorable` scope)
- If you have some commission changes locally, edit related validator manually and set is_active to false
- Commission changes for this validator should now be visible
- On staging test on this validator: https://stage.validators.app/commission-changes/179 before and after deploying this branch (it's inactive, but changed its commission recently, so you should see some records after deploy)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184371776)
- [N] …
> 184371776 Show all commission changes

- app/javascript/packs/commission_histories/commission_history_row.js
- app/javascript/packs/commission_histories/index_template.vue
- app/models/epoch_wall_clock.rb
- app/queries/commission_history_query.rb
- change batch to source in commissions table
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184371796)
> 184371796-show-source-not-batch

- app/views/public/api_documentation.html.erb
- As in PR title 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184379873)
> 184379873 Update API docs for commissio changes

- app/views/layouts/_footer.html.erb
- display hostname in footer
- only on servers
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184376394)
> 184376394 hostname in footer

- app/services/track_commission_changes_service.rb
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184528375)
> 184528375-fix-commission-changes-detection

- config/environments/development.rb
- config/environments/production.rb
- Configures default cache store
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184557700)
> 184557700 configure cache store

- app/views/public/api_documentation.html.erb
- Fix sample response in API documentation for ping things post 
- see the docs
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184585519)
> 184585519-fix-api-doc-for-ping-things

- app/services/total_rewards_update_service.rb
- allow 0 stakes to be taken into account for pythnet
- test on staging (check ROI for pythnet)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184581886)
> 184581886-fix-roi-for-pythnet

- app/javascript/packs/validators/validator_details.vue
- add refresh button to validator details
- check if the button works
- check console for errors
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184620462)
> 184620462-validator-details-refresh-button

- app/controllers/api/v1/stake_accounts_controller.rb
- test/controllers/api/v1/stake_accounts_controller_test.rb
- remove unnecessary empty pages from the back of the stake pools index
- run tests
- check vue index
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184626703)
> 184626703 - fix total_count in stake pools controller

- app/models/ping_thing.rb
- app/models/ping_thing_raw.rb
- app/services/process_ping_things_service.rb
- app/services/recalculate_ping_thing_stats_service.rb
- app/workers/recalculate_ping_thing_stats_worker.rb
- test/models/ping_thing_test.rb
- test/services/recalculate_ping_thing_stats_service_test.rb
> tweak-ping-thing-performance

- app/javascript/packs/navigations/validator_searcher_bar_template.vue
- app/views/validators/_search_bar.html.erb
- Updates search field placeholder
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184673043)
> 184673043 - Update search filed placeholder

- config/initializers/rack_attack.rb
- Create rack key if user token is present
- Send som API GET requests in small time intervals (eg. https://stage.validators.app/api-documentation?locale=en&network=mainnet#ping), with correct token, then with incorrect token, then without any token, and compare results.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184723973)
> 184723973 handle no method error

- app/helpers/application_helper.rb
- app/helpers/validators_helper.rb
- app/javascript/packs/validators/validator_row.js
- app/views/validators/_table.html.erb
- test/factories/validators.rb
- test/helpers/validators_helper_test.rb
PR fixes the names for validators.
- verify if validators in the stake pools page are valid (its names)
- example validator https://www.validators.app/validators/28rsUPxFhKWhrHsyxDBQSccDtVriCSriDJRfsU1eYyP6?network=mainnet
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184694688)
> 184694688 - fix private validator names

- script/remove_unconfirmed_users.rb
- test/factories/user.rb
- test/scripts/remove_unconfirmed_users_test.rb
- adds removing users that did not log in within 7 days
- run tests
- create users and check if they're deleted properly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184689543)
> 184689543-remove-users-without-log_in

- Gemfile.lock
As in the title above.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859#)
> 184529687 - upgrade version of solana rpc ruby gem

- app/assets/stylesheets/buttons.scss
- app/views/validators/_watchlist_info_banner.html.erb
- Moves "sign up now" button on watchlist card
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184844961)
> Move sign up button to the right

- app/services/validator_check_active_service.rb
- test/services/validator_check_active_service_test.rb
- fix updating validators active status 
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184780382)
> 184780382-fix-updating-validator-active-status

- app/javascript/packs/validators/validator_details.vue
Adds creation date to validator details page.
- verify the field placed in the validator details section
- the format should be unified as the other date occurrences. In details page you can scroll down and check the "Recent Block Production" section.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184522955)
> 184522955 - add creation date to validator details page

- app/services/validator_check_active_service.rb
- test/services/validator_check_active_service_test.rb
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184856394)
> fix-slow-validator-check-active-service

- app/assets/images/jito-logo.svg
Add new jito sol logo.
Check displaying the logo - e.g. validators, stake pools page.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184846344)
> 184846344 - add new jito sol logo

- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/stake_accounts/pool_stats.js
- app/javascript/packs/stake_accounts/pools_overview.js
- app/javascript/packs/validators/circulating_supply.vue
- app/logic/stake_logic/apy_helper.rb
- app/views/public/faq.en.html.erb
- Change APY to ROD in all the descriptions
- make sure it is changed in all of the places
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184296746)
> 184296746-apy-to-rod

- app/services/data_centers/check_ip_info_service.rb
> 184884133-replace-en-with-gb

- app/views/public/home.html.erb
- app/views/validators/_watchlist_info_banner.html.erb
- Review in the browser and confirm that the issue described in PT story is no longer there
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184928505)
> 184928505 Fix watchlist button alignment for pythnet

- app/services/data_centers/check_ip_info_service.rb
- unify country name for data centers
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184928610)
> 184928610-unify-dc-country-name

- app/javascript/packs/validators/charts/block_history_chart.js
- app/javascript/packs/validators/charts/skipped_slots_large_chart.js
- app/javascript/packs/validators/charts/vote_history_chart.js
- app/javascript/packs/validators/validator_details.vue
- validator details page should refresh via axios and vue instead of page refresh
- run pipeline daemons
- go to validator page
- data should be reloaded every 3 minutes
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183985579)
> 183985579 live update validator details

- app/services/data_centers/check_ip_info_service.rb
- Fixes undefined method for unknown DC
- Run `https://www.pivotaltracker.com/story/show/184928610`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184928610)
> 184928610 Fix undefined downcase method

- app/javascript/packs/application.js
- app/javascript/src/chart_links.js
- app/javascript/src/score_modal_trigger.js
- app/javascript/src/watch_buttons.js
- config/webpack/environment.js
- package.json
- yarn.lock
- Removes jquery lib
- Install yarn packages
- Click throught the website
- Check if the rewrited script works the same as before (adding and removing validators to favourites by clicking on star icon)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184931862)
> 184931862 Remove jquery

- app/models/stats/validator_score.rb
- app/queries/validator_score_query.rb
- vote distance and root distance stats on home page should include only active validators
- test front stats update daemon if it returns no errors
- run tests
- test on staging if the values look correct
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184961000)
> 184961000 fix distance stats

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/images.scss
- app/assets/stylesheets/tables.scss
- app/helpers/validators_helper.rb
- app/javascript/packs/validators/charts/skipped_vote_speedometer.js
- app/javascript/packs/validators/validator_details.vue
- app/javascript/packs/validators/validator_row.js
- app/javascript/src/chart_links.js
- app/views/validators/_table.html.erb
- app/views/validators/_toggle_bar.html.erb
- Tweaks validators table alignment
- Review in the browser
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184821527)
> 184821527 tweak validators table alignment

- config/schedule.rb
As in the title.
The only way to test it is to make a deploy on staging and verify if the `gather_stake_accounts` runs every 2 hours.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184549017)
> 184549017 - change gather_stake_accounts schedule for every other hour

- app/controllers/data_centers_controller.rb
- in data center details page we search for dc by data_center_key. this PR changes displayed data_center from first to last record
- stage
- https://www.pivotaltracker.com/story/show/184608178
> 184608178-show-current-data-center-in-details-page

- app/javascript/packs/validators/validator_details.vue
- Wraps long text, like the link attached to PR story
- Check validator details page in the browser. Examples on staging:
https://stage.validators.app/validators/5NiHw5LZn1FiL848XzbEBxuygbNvMJ7CsPvXNC8VmCLN?locale=en&network=mainnet
https://stage.validators.app/validators/CquA9q57TYVr9uvXvk6aqAG5GGKk3mUL9C8ALyAsUeWg?locale=en&network=mainnet
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184977331)
> 184977331 Wrap long text on validator details page

- app/models/validator.rb
- app/views/asns/show.html.erb
- app/views/data_centers/_asn_head.html.erb
- app/views/data_centers/_asn_list.html.erb
- app/views/data_centers/_data_center_head.html.erb
- app/views/data_centers/_data_center_list.html.erb
- app/views/data_centers/_filters.html.erb
- app/views/data_centers/data_center.html.erb
- test/models/validator_test.rb
Remove inactive filters and TOTAL stake reference over DC pages.
- verify filters in DC pages( index, show and ASN related versions)
- Total Stake was renamed into Stake. Please verify that.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184855662)
> 184855662 - remove inactive filters

- app/controllers/public_controller.rb
- app/views/public/api_documentation.html.erb
- It sets dynamic paths in API docs examples
- Go to /api-documentation and confirm that paths are displayed correctly
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184582826)
> 184582826 tweak paths in api docs

- Gemfile.lock
- app/models/epoch_wall_clock.rb
- app/services/process_ping_things_service.rb
- app/workers/ping_thing_stats_worker.rb
- app/workers/validator_score_v1_worker.rb
- config/schedule.rb
- daemons/validator_score_mainnet_v1_daemon.rb
- daemons/validator_score_pythnet_v1_daemon.rb
- daemons/validator_score_testnet_v1_daemon.rb
Reverts brianlong/www.validators.app#804
Incompatibile redis version https://appsignal.com/first-movers-advantage-llc/sites/6043bed214ad6641f161a691/exceptions/incidents/232
> Revert "Bump sidekiq from 6.4.0 to 7.0.8"

- app/services/data_centers/remove_without_validators_and_gossip_nodes.rb
- update script removing duplicated DC's
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185030166)
> 185030166-remove-duplicated-dcs

- app/javascript/packs/validators/validator_details.vue
PR applies shuffled delegation buttons.
- verify the buttons, its name, descriptions, href
- check if they are randomized
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185201502)
> 185201502 - randomize delegate links

- app/views/public/faq.en.html.erb
As in the title.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185293569)
> 185293569 - udpate faq

- app/javascript/packs/validators/validator_details.vue
- deactivate url for validator website in validator details page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185308193)
> 185308193-remove-link-to-validator-websites

- app/models/group.rb
- app/models/group_validator.rb
- app/services/check_group_validator_assignment_service.rb
- db/migrate/20230602132048_add_network_to_groups.rb
- db/migrate/20230605085152_add_reason_to_group_validators.rb
- db/schema.rb
- script/backfill_validator_groups.rb
- test/services/check_group_assignment_service_test.rb
- as in title
- run tests
- run `rails r script/backfill_validator_groups.rb`
- check logs `log/backfill_validator_groups_mainnet.log`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185257278)
> 185257278 backfill validator groups

- app/controllers/api/v1/data_centers_controller.rb
- app/javascript/packs/data_centers/data_center_charts.js
- app/javascript/packs/data_centers/data_center_charts.vue
- app/javascript/packs/data_centers/pie_chart.js
- app/views/asns/show.html.erb
- app/views/data_centers/data_center.html.erb
- app/views/data_centers/index.html.erb
- app/views/layouts/_footer.html.erb
- config/routes.rb
- test/controllers/api/v1/data_centers_controller_test.rb
- add charts related to country and organization to data center index page
- check the charts
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184041081)
> 184041081 add charts to datacenters

- app/logic/report_logic.rb
- test/logic/report_logic_test.rb
Fixes `comparison of Float with nil failed` when active stake is nil in Software Versions.
- `rails test`
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185455392)
> 185455392 - Fix front_stats_update service

- app/controllers/concerns/validators_controller_helper.rb
- app/models/validator.rb
- app/models/validator_history.rb
- app/queries/validator_query.rb
- test/models/validator_history_test.rb
- test/models/validator_test.rb
Reverts brianlong/www.validators.app#820
> Revert "185232287 - fix api validator response"

- app/assets/stylesheets/buttons.scss
- app/javascript/packs/validators/validator_details.vue
- app/models/validator.rb
- app/views/validators/_table.html.erb
- db/migrate/20230621124736_add_jito_commission_to_validators.rb
- db/schema.rb
- script/update_jito_validators.rb
- test/scripts/update_jito_validators_test.rb
- add jito mark to validators in validators table and show jito commission in detail view
- run migration
- run script/update_jito_validators.rb
- check validators table and details
> 185395899 mark jito validators

- app/javascript/packs/validators/validator_details.vue
- fix displaying jito badge in validator details
> 185395899 - jito-badge-only-for-jito-validators

- app/javascript/packs/validators/validator_details.vue
- show jito commission as percentage
> fix-jito-commission

- app/controllers/ping_things_controller.rb
- app/javascript/packs/ping_things/ping_thing_header.vue
- app/views/layouts/_flash.html.erb
- adding flash message to Ping Thing page.
- check the message at the top of the Ping Thing page.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185496709)
> 185496709 - Add Message to Ping Thing Page

- app/controllers/api/v1/account_authority_controller.rb
- app/controllers/public_controller.rb
- app/javascript/packs/account_authority_histories/index.js
- app/javascript/packs/account_authority_histories/index_template.vue
- app/models/account_authority_history.rb
- app/queries/account_authority_query.rb
- app/views/layouts/_footer.html.erb
- app/views/public/authorities_changes.html.erb
- config/routes.rb
- create a page with recent authority changes
- visit `https://stage.validators.app/authorities_changes`
- check pagination
- check if links are working as expected
- check page for all networks
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185454173)
> 185454173 show all authorities changes

- app/assets/stylesheets/alerts.scss
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185496709)
> 185496709 - fix css for mobile

- app/models/epoch_wall_clock.rb
- app/views/public/api_documentation.html.erb
- app/views/public/faq.en.html.erb
- test/controllers/api/v1/epochs_controller_test.rb
- add total_rewards and total_active_stake to epochs api
- run tests
- check the endpoint `http://localhost:3000/api/v1/epochs/:network.json`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185561636)
> 185561636 update epochs api

- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/images.scss
- app/assets/stylesheets/tables.scss
- app/controllers/ping_things_controller.rb
- app/javascript/packs/account_authority_histories/index_template.vue
- app/javascript/packs/mixins/validators_mixins.js
- app/javascript/packs/ping_things/ping_thing_header.vue
- app/javascript/packs/validators/validator_details.vue
- app/javascript/packs/validators/validator_row.js
- app/views/layouts/_footer.html.erb
- app/views/public/api_documentation.html.erb
- app/views/public/authorities_changes.html.erb
- app/views/validators/_table.html.erb
- Tweaks css and page responsiveness
- Click through authorities histories, ping thing and validators index pages and check issues listed in PT.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185551844)
> 185551844 fix page responsiveness

- app/views/validators/_stake_pools_banner.html.erb
- Apply brand change: https://twitter.com/brianlong/status/1692255151971533183?s=61&t=rplgDdn7lt9G8qMR0c-jnw
- Run the server and check the homepage
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185860390)
> 185860390 update unstake it address

- app/views/layouts/_flash.html.erb
- As in title
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185872666)
> 185872666 Fix flash error

- app/controllers/api/v1/validators_controller.rb
- app/views/public/api_documentation.html.erb
- config/routes.rb
- test/controllers/api/v1/validators_controller_test.rb
- add api endpoint for ledger live featuring validator details
- run tests
- check `http://localhost:3000/api/v1/validators-ledger/:network/:account` 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185957331)
> 185957331-ledger-live-api

- config/routes.rb
- test/controllers/data_centers_controller_test.rb
- Handle dc links with dots
- run tests
- check dc with dots in data_center_key or update one. Make sure that the link works correctly 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186040264)
> 186040264-fix-dc-link

- config/schedule.rb
- Move jobs to different hours
> Tweak schedule

- app/services/track_commission_changes_service.rb
- test/services/track_commission_changes_service_test.rb
- test/vcr_cassettes/services/track_commission_changes_service/track_commission_changes_service_test_no_epoch.yml
- as in title
- run tests
- check on staging
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186212202)
> 186212202-fix-no-method-error-for-commission-changes-service

- app/queries/commission_history_query.rb
- app/services/track_commission_changes_service.rb
- test/models/validator_test.rb
- test/queries/commission_history_query_test.rb
- avoid creating duplicates for commission histories
- test on staging after new epoch emerges
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186263512)
> 186263512 avoid duplicates while adding commission history

- app/models/epoch_wall_clock.rb
> TrackCommissionChangesWorker does not run on production

- app/queries/explorer_stake_account_query.rb
- make sure the explorer stake accounts views are never empty
- run tests
- check if there are no empty explorer stake account views after new epoch shows up
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186322522)
> 186322522-tweak-epoch-detection

- app/javascript/packs/validators/components/validator_score_modal.vue
- as in title
- update or find validator with consensus_mods_score = -2
- make sure it displays correctly in score modal in validator show page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186337402)
> 186337402-fix-mods-scores-in-modal

- app/javascript/packs/stake_accounts/stake_account_row.js
- add links for staker, withdrawer and stake pubkey in stake pools table
- check if all of the links in stake pools view (table) work as expected
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186372351)
> 186372351-link-accounts-in-stake-pool

- config/schedule.rb
- dev/keep_creating_ping_things.rb
- run sidekiq and `dev/keep_creating_ping_things.rb`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186526677)
> 186526677 Move PingThingStatsWorker to high priority queue

- app/services/create_ping_thing_stats_service.rb
- dev/keep_creating_ping_things.rb
- prevent nil/0 tps
- run sidekiq
- run `rails r dev/keep_creating_ping_things.rb`
- confirm that ping thing stats are populated
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186502765)
> 186542716 fix ping thing tps for pythnet

- app/controllers/api/v1/validators_controller.rb
- app/controllers/concerns/validators_controller_helper.rb
- app/controllers/validators_controller.rb
- app/models/validator.rb
- app/queries/validator_query.rb
- app/views/public/api_documentation.html.erb
- test/controllers/api/v1/validators_controller_test.rb
- test/queries/validator_query_test.rb
- set random order of the results by score
- remove inactive validators from default query (make it optional)
- add is_active field to API response
- update docs
- check if the docs are updated
- run tests
- try to send requests to /api/v1/validators/:network with various params and see if they match the documentation description
- make sure there are no inactive validators by default
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186547814)
> 186547814 update validators api

- app/views/stake_accounts/_explorer_stake_accounts.html.erb
- links for staker and withdrawer lead directly to stake explorer
- check vote account details page and stake explorer page
- confirm correct behaviour of links
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186644748)
> 186644748-change-links-in-stake-explorer

- app/assets/stylesheets/tables.scss
- app/controllers/concerns/validators_controller_helper.rb
- app/controllers/validators_controller.rb
- app/logic/solana_logic.rb
- app/logic/validator_score_v1_logic.rb
- app/models/validator.rb
- app/models/validator_block_history.rb
- app/models/validator_score_v1.rb
- app/views/public/api_documentation.html.erb
- app/views/validators/_table.html.erb
- test/controllers/api/v1/validators_controller_test.rb
- as in title
- run gather and score daemons
- check if ValidatorBlockHistory records are populated with skipped_after and skipped_after_percvent
- check if ValidatorScoreV1s are populated with skipped_after_history
- check validators index page - make sure the skipped_after metric is displayed properly
> 186655494 bring back skipped after

- app/assets/stylesheets/tables.scss
- app/controllers/concerns/validators_controller_helper.rb
- app/logic/solana_logic.rb
- app/logic/validator_score_v1_logic.rb
- app/models/validator.rb
- app/models/validator_block_history.rb
- app/models/validator_score_v1.rb
- app/views/public/api_documentation.html.erb
- app/views/validators/_table.html.erb
- test/controllers/api/v1/validators_controller_test.rb
Reverts brianlong/www.validators.app#902
> Revert "186655494 bring back skipped after"

- app/services/create_ping_thing_stats_service.rb
- allow delay between pt stats to avoid skipping minutes
- add ping things using interval and check the logs at /log/ping_thing_stats_service.log
- make sure there are no skipped 1-minute stats
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186672407)
> 186672407 fix missing pt stats

- app/assets/stylesheets/forms.scss
- app/controllers/api/v1/ping_things_controller.rb
- app/javascript/packs/ping_things/index_template.vue
- app/javascript/packs/ping_things/ping_thing_table.vue
- app/views/public/api_documentation.html.erb
- dev/create_test_ping_things.rb
- test/controllers/api/v1/ping_things_controller_test.rb
- Adds filters for pings table
- reduces size of pings table
- Make sure you have at least 2 users in your db - if not, create more
- Run the script to populate db: `rails r dev/create_test_ping_things.rb` (you can repeat this script multiple times if you need to generate more data)
- Go to Ping Thing page and test the filters on table - use each filter separately, use the combination of different filters, and confirm that they work correctly. Use also invalid values and confirm that filters still work correctly.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186700360)
- …
> 186700360 add filters to pings table

- Gemfile
- app/helpers/validators_helper.rb
- app/models/validator.rb
- app/services/update_avatar_file_service.rb
- daemons/concerns/leader_stats_helper.rb
- Check avatar links in UI and API
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186664148)
> 186664148 Update avatar url

- app/views/layouts/_footer.html.erb
- app/views/public/home.html.erb
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186761018)
> 186761018 Switch headings order on home page

- app/views/layouts/_footer.html.erb
- As in PR title 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186767931)
> 186767931 Add missing turbolikns data property

- Capfile
- app/controllers/public_controller.rb
- config/deploy.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/stage.rb
- config/routes.rb
- config/schedule.rb
- Fixes configuration that provides sitemap file
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186442321)
> Fix sitemap config

- app/helpers/validators_helper.rb
- app/javascript/packs/clusters/cluster_performance_stats_component_template.vue
- app/javascript/packs/stake_accounts/index_template.vue
- app/javascript/packs/validators/charts/block_history_chart.js
- app/javascript/packs/validators/charts/skipped_vote_speedometer.js
- app/javascript/packs/validators/charts/vote_history_chart.js
- app/views/validators/_table.html.erb
- app/views/vote_accounts/_vote_account_histories_table.html.erb
- config/environments/development.rb
- config/locales/en.yml
- As in PR title 
- Check validators table on home page and stake pools page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186760532)
> 186760532 update metrics names

- config/deploy.rb
- config/deploy/production.rb
- config/schedule.rb
- Moves sitemap tasks to web servers
- Deploy
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186779099)
> 186779099 fix sitemap config

- app/javascript/packs/stake_accounts/index_template.vue
- app/views/validators/_table.html.erb
- daemons/gather_rpc_pythnet_daemon.rb
- Run both pythnet deamons
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186844377)
> 186844377 add sleep to pythnet deamon

- app/services/update_avatar_file_service.rb
- dispose of all unused images from /tmp directory
- run script/validators_update_avatar_files.rb and check if there are any images/gifs left after the process
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186664135)
> remove unconverted images

- app/controllers/api/v1/validators_controller.rb
- app/javascript/packs/validators/charts/skipped_after_large_chart.js
- app/logic/solana_logic.rb
- app/models/batch.rb
- db/migrate/20240119104342_add_skipped_after_average_to_batches.rb
- db/schema.rb
- add skipped after history to batches
- run migration
- run tests
- run gather and score daemons to populate db
- check if average_skipped_after is populated correctly in batches
- check the chart in validator details page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186861127)
> 186861127 cluster skipped after in batches

- dev/asn_logic_demo.rb
- dev/collector_demo.rb
- dev/create_test_ping_things.rb
- dev/gather_vote_account_details_force_update.rb
- dev/keep_creating_ping_things.rb
- dev/report_logic_demo.rb
- dev/report_software_version_demo.rb
- dev/show_account_history.rb
- dev/skipped_slots_after_leader.rb
- dev/solana_network_stats.rb
- dev/solana_pipeline_demo.rb
- dev/stake_logic_demo.rb
- Add logic preventing execution of dev scripts on production
- run all dev scripts and check if they are running od production env (RAILS_ENV=production). It raise a proper warning.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186934110)
> 186934110 - add warnings to dev scripts

- app/logic/validator_score_v1_logic.rb
- app/models/stats/validator_block_history.rb
Reverts brianlong/www.validators.app#942
> Revert "186912538 Remove duplicated query and simplify code"

- app/javascript/packs/ping_things/user_stats.vue
- Visual tweaks
- As in parent story
> Tweak user stats alignment

- app/javascript/packs/clusters/cluster_performance_stats_component_template.vue
- Tweaks skipped slot stats.
- run the daemon and verify skipped slot stats.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186731063)
> 186731063 - Round skipped slot stats

- app/javascript/packs/ping_things/index_template.vue
- app/javascript/packs/ping_things/user_stats.vue
- move ping thing user chart under the charts
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186961215)
> 186961215 move pt users under the charts

- app/javascript/packs/ping_things/ping_thing_table.vue
- app/javascript/packs/ping_things/user_stats.vue
- latency -> slot latency
- remove ms from latency column
- half the number of ping thing records in a table
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186963893)
> remove ms from latency + half the number of pt displayed

- .github/workflows/pronto.yml
- As in the title.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186943290)
> 186943290 - Fix pronto setup in validators

- app/javascript/packs/ping_things/index_template.vue
- app/javascript/packs/ping_things/user_stats.vue
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186981905)
> 186981905 tweak pings tabs display

- config/schedule.rb
- As in PR title 
- Check crontab after deploy
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187028260)
> 187028260 Update script name

- .github/workflows/test_suite.yml
- As in the title.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180960886)
> 180960886 - update github workflow versions

- test/controllers/opt_out_requests_controller_test.rb
- Removes assert_response :redirect occurrences.
- `rails test`
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182388659)
> 182388659 - Change assert_response :redirect

- app/services/data_centers/change_validator_data_center.rb
- script/data_centers_scripts/change_validator_data_center.rb
- test/services/data_centers/change_validator_data_center_test.rb
- Move validator_id argument to call action in service.
- `rails test`
- run `rails r script/data_centers_scripts/change_validator_data_center.rb` and check if any error occurs.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183012691)
> 183012691 - Update service to change validator data centers

- app/models/concerns/archivable.rb
- app/models/stake_account_history_archive.rb
- db/migrate/20240205123006_create_stake_account_history_archives.rb
- db/schema.rb
- script/archives/archive_stake_account_history.rb
- test/factories/stake_account_history_archives.rb
- test/models/concerns/archivable_test.rb
- test/models/stake_account_history_archive_test.rb
- Archive older data from tables
- run tests
- populate StakeAccountHistory table with records older than 2 months
- run `rails r script/archives/archive_stake_account_history.rb`
- check if the records were moved to StakeAccountHistoryArchieve table
- [StakeAccountHistory](https://www.pivotaltracker.com/story/show/186901610)
> 186901610 archive old tables

- app/javascript/packs/mixins/stake_pools_mixins.js
- app/javascript/packs/stake_accounts/pool_stats.js
- app/models/stake_pool.rb
- config/initializers/stake_pools_data.rb
- script/one_time_scripts/remove_stake_pool.rb
- Updates stake pools information.
- `rails add_stake_pools:mainnet` and `rails update_fees_in_stake_pools:mainnet` check stake pools fees information at /stake-pools
- `rails r script/one_time_scripts/remove_stake_pool.rb 'Eversol' 'mainnet'` should remove Eversol stake pool and its relations.
- run `rails r script/update_validator_stake_pools_list.rb` script 
- click through the app - validators index, stake pools pages
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187078079)
> 187078079 - update stake pools

- config/application.rb
- config/cable.yml
- config/database.example.yml
- config/environments/production.rb
- As in the title.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/178127351)
> 178127351 - change application name

- config/initializers/stake_pools_data.rb
- jito fee 4 -> 5
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187186762)
> 187186762-update-jito-manager-fee

- app/models/blockchain.rb
- app/models/blockchain/slot.rb
- app/services/blockchain/get_leader_schedule_service.rb
- config/schedule.rb
- db/migrate/20240308093154_create_blockchain_slots.rb
- db/schema.rb
- script/blockchain/get_leaders_schedule.rb
- test/factories/blockchain/slots.rb
- test/models/blockchain/slot_test.rb
- test/services/blockchain/get_leader_schedule_service_test.rb
create blockchain slots
download leader schedule
- run tests
- run `rails r script/add_current_epoch.rb`
- run `rails r script/blockchain/get_leaders_schedule.rb`
- check if the slots are added correctly
- in the second run no slots should be added (should download schedule only once per epoch)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187183914)
> 187183914 leaders schedule

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/typography.scss
- app/controllers/api/v1/ping_thing_user_stats_controller.rb
- app/javascript/packs/mixins/strings_mixins.js
- app/javascript/packs/ping_things/index_template.vue
- app/javascript/packs/ping_things/stats_bar.vue
- app/javascript/packs/ping_things/stats_chart.js
- app/javascript/packs/ping_things/user_stats.vue
- app/models/ping_thing.rb
- app/models/ping_thing_recent_stat.rb
- app/models/ping_thing_user_stat.rb
- app/services/create_ping_thing_stats_service.rb
- app/services/ping_thing_user_stats_service.rb
- db/migrate/20240313120335_add_latency_columns_to_ping_stats.rb
- db/schema.rb
- dev/create_test_ping_things.rb
- dev/keep_updating_recent_ping_stats.rb
- test/models/ping_thing_recent_stat_test.rb
- test/services/ping_thing_user_stats_service_test.rb
- adds latency stats and redos views
- On staging:
- run `RAILS_ENV=stage bundle exec rails r dev/create_test_ping_things.rb` (you can run multiple times)
and review https://stage.validators.app/ping-thing page
- Locally:
- run sidekiq
- populate db with `rails r dev/create_test_ping_things.rb`  (run a couple of times)
- review on /ping-thing page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187200668)
> 187200668 add latency columns

- Gemfile
- Gemfile.lock
- app/services/blockchain/slot_subscribe_service.rb
- daemons/blockchain/slot_subscribe_mainnet.service
- daemons/blockchain/slot_subscribe_mainnet_daemon.rb
- daemons/blockchain/slot_subscribe_pythnet.service
- daemons/blockchain/slot_subscribe_pythnet_daemon.rb
- daemons/blockchain/slot_subscribe_testnet.service
- daemons/blockchain/slot_subscribe_testnet_daemon.rb
- daemons/slot_subscribe_mainnet_daemon.rb
- create daemons for all networks that connect to slotSubscribe solana websocket and receive a message about new slots 
- bundle
- run `rails r daemons/blockchain/slot_subscribe_mainnet_daemon.rb`
- check the log at log/slot_subscribe_service_mainnet.log
- there should be a stream of new messages with current slots
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187231156)
- [Y] Does this PR add new dependencies?
> 187231156 slot subscribe daemon

- daemons/gather_rpc_mainnet_daemon.rb
- daemons/gather_rpc_pythnet_daemon.rb
- daemons/gather_rpc_testnet_daemon.rb
- daemons/validator_score_mainnet_v1_daemon.rb
- daemons/validator_score_pythnet_v1_daemon.rb
- daemons/validator_score_testnet_v1_daemon.rb
- Deploy to staging and review batch creation times
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187336905)
> 187336905 slow down daemons on staging

- app/models/validator_ip.rb
- app/queries/gossip_node_query.rb
- db/migrate/20240403104942_add_index_to_validator_ips.rb
- db/schema.rb
-  the gossip API endpoint with pagination is extremely slow to respond to queries
- run migration
- test the API endpoint `http://localhost:3000/api/v1/gossip-nodes/<network>` with various page and per
- test the endpoint times
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187321421)
> 187321421-fix-slow-gossip-nodes-query

- daemons/gather_rpc_mainnet_daemon.rb
- daemons/gather_rpc_pythnet_daemon.rb
- daemons/gather_rpc_testnet_daemon.rb
- daemons/validator_score_mainnet_v1_daemon.rb
- daemons/validator_score_pythnet_v1_daemon.rb
- daemons/validator_score_testnet_v1_daemon.rb
This reverts https://github.com/brianlong/www.validators.app/pull/989
> Revert "187336905 slow down daemons on staging (#989)"

- app/views/public/faq.en.html.erb
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187418856)
> 187418856 Fix typo

- app/javascript/packs/ping_things/ping_thing_table.vue
- app/javascript/packs/ping_things/stats_bar.vue
- app/javascript/packs/ping_things/user_stats.vue
- change "failures" to "errors" in a ping thing tables
- check the ping thing page and make sure all the "failure" headers is changed to "errors"
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187440893)
> 187440893-ping-thing-failures-to-errors

- dev/ping_things_history_to_csv.rb
> dev script to download ping things

- app/models/blockchain/block.rb
- app/models/blockchain/slot.rb
- app/services/blockchain/get_block_service.rb
- app/services/blockchain/get_leader_schedule_service.rb
- app/services/blockchain/slot_subscribe_service.rb
- app/workers/blockchain/get_block_worker.rb
- db/migrate/20240326095333_create_blockchain_blocks.rb
- db/migrate/20240327123816_add_status_to_blockchain_slots.rb
- db/schema.rb
- test/factories/blockchain/blocks.rb
- test/factories/blockchain/slots.rb
- test/models/blockchain/block_test.rb
- test/models/blockchain/slot_test.rb
- test/services/blockchain/get_block_service_test.rb
- test/services/blockchain/get_leader_schedule_service_test.rb
- create sidekiq job to process new blocks
- run tests
- turn on sidekiq
- run `rails r daemons/blockchain/slot_subscribe_mainnet_daemon.rb`
- check if new blocks are being created
- check if slot statuses are updated correctly
> 187231189 sidekiq create blocks

- .gitignore
- config/deploy.rb
- config/sidekiq_blockchain.yml.example
- create another sidekiq instance for blockchain queue
- Create sidekiq_blockchain.yml (see example file added in this PR)
- Test running the second sidekiq instance with `bundle exec sidekiq --config ./config/sidekiq_blockchain.yml`. Confirm that both sidekiq instances are running without errors
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187462816)
> 187462816 sidekiq for blockchain

- config/deploy.rb
- Moves systemd services management to background server
- Deploy to staging
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187462816)
> 187462816 Tweak new sidekiq configuration

- config/deploy.rb
- config/deploy/production.rb
- script/blockchain/get_leaders_schedule.rb
- Updates capistrano with new system services
- Deploy to staging and confirm that only mainnet deamon is restarted
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187484158)
> 187484158 update capistrano config

- app/models/blockchain/block.rb
- app/models/blockchain/block_archive.rb
- app/models/blockchain/transaction.rb
- app/models/blockchain/transaction_archive.rb
- app/models/concerns/archivable.rb
- app/services/blockchain/get_block_service.rb
- db/migrate/20240507112211_add_network_and_epoch_to_blockchain.rb
- db/schema.rb
- script/archives/archive_blockchain.rb
- test/scripts/archives/archive_blockchain_test.rb
- add network and epoch to blockchain block and blockchain transaction
- run tests
- get last epoch by `rails r script/add_current_epoch.rb`
- add slots `rails r script/blockchain/get_leaders_schedule.rb`
- start sidekiq with blockchain queue
- Run `rails r daemons/blockchain/slot_subscribe_<network>_daemon.rb`
- check if Blockchain::Slots, Blockchain::Blocks, Blockchain::Transactions have network and epoch 
- try to archive created records by `rails r script/archives/archive_blockchain.rb`, but change EPOCHS_KEPT value in the script to 0
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187516948)
- …
> 187516948 network for blocks and transactions

- app/services/blockchain/get_block_service.rb
> 187569003 speed up blockchain transactions

- script/update_jito_validators.rb
- add logs to jito script
- run `rails r script/update_jito_validators.rb`
- check logs at `tail log/update_jito_validators.log`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187624672)
> add logs to jito script

- app/models/blockchain/block.rb
- app/models/concerns/archivable.rb
- db/migrate/20240522065603_add_index_to_blockchain_blocks.rb
- db/schema.rb
- script/archives/archive_blockchain.rb
> 187642717 fix archive script

- app/services/blockchain/get_block_service.rb
- fix sending error to appsignal
> 187697830-fix-typeerror-in-blockchain-service

- Gemfile
- Gemfile.lock
- app/models/concerns/archivable.rb
- config/deploy.rb
- script/archives/archive_blockchain.rb
> 187642717 speed up transaction delete query

- app/controllers/api/v1/ping_thing_user_stats_controller.rb
- app/javascript/packs/ping_things/user_stats.vue
- dev/create_test_ping_things.rb
- dev/keep_creating_ping_things.rb
- Sorts user stats by number of entries
- run `dev/keep_creating_ping_things.rb` and review ping thing page
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187800656)
> 187800656 change sorting on ping thing

- .github/workflows/pronto.yml
> Add gems versions to pronto github action

- app/services/gatherers/vote_account_details_service.rb
- get rid of constant connectionNotEstablished error on prod
> 187982449-fix-va-connectionNotEstablished

- app/services/blockchain/archive_blockchain_service.rb
- config/deploy.rb
- daemons/blockchain/slot_subscribe_mainnet_daemon.rb
- daemons/blockchain/slot_subscribe_pythnet_daemon.rb
- daemons/blockchain/slot_subscribe_testnet_daemon.rb
- daemons/sidekiq.service
- daemons/sidekiq_blockchain.service
- script/archives/archive_blockchain.rb
- script/blockchain/check_error_slots.rb
- script/blockchain/get_leaders_schedule.rb
> Turn off  networks other than mainnet

- app/services/blockchain/get_block_service.rb
- add rescue logic for saving transactions
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187963991)
> 187963991-tweak-errors-management-for-blockchain-transactions

- .github/workflows/pronto.yml
- Updates pronto config
- Confirm that all gh checks passed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188084035)
> 188084035 Upgrade pronto config

- app/controllers/api/v1/base_controller.rb
- app/logic/solana_logic.rb
- app/logic/validator_score_v1_logic.rb
- check the db lock errors and handle it
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188070724)
> 188070724-handle-db-errors

- .github/workflows/pronto.yml
- Gemfile
- Gemfile.lock
> Upgrade node and webpacker pronto

- package.json
- yarn.lock
- dependabot updates
- yarn install
- rails assets:precompile
- run tests
- go through the app and check for errors
> 188296445 dependabot updates

- Gemfile
- Gemfile.lock
- app/workers/blockchain/get_block_worker.rb
- config/initializers/sidekiq.rb
- config/routes.rb
- make sure that there are no sidekiq jobs duplicates
- bundle install
- start sidekiq
- run `rails r daemons/blockchain/slot_subscribe_mainnet_daemon.rb`
- check if there are no duplicates in the queue
- [Y] Does this PR add new dependencies?
> 188435529-fix-sidekiq-duplicates

- app/controllers/api/v1/data_centers_controller.rb
- app/controllers/data_centers_controller.rb
- app/javascript/packs/data_centers/data_center_charts.js
- app/javascript/packs/data_centers/data_center_charts.vue
- app/javascript/packs/data_centers/pie_chart.js
- app/models/data_center_stat.rb
- app/services/data_centers/fill_data_center_stats.rb
- app/services/sorted_data_centers.rb
- app/views/data_centers/index.html.erb
- db/migrate/20241118131225_add_active_validators_stake_to_data_center_stats.rb
- db/schema.rb
- test/controllers/api/v1/data_centers_controller_test.rb
- test/services/sorted_data_centers_test.rb
- sort data center index by count or stake
- run tests
- go to /data-centers page
- try stake/count buttons and check if sorting is correct
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188556732)
> 188556732 dc pie charts by stake

- app/controllers/sessions_controller.rb
- config/routes.rb
- bad csrf token while login results in reset session instead of exception
- test login/signup pages
- there should be no more ActionController::InvalidAuthenticityToken errors from login 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188611201)
> 188611201-fix-422-after-failed-login

- app/javascript/packs/validators/validator_details.vue
- remove marinade stake button from validator details view
- check if the button is gone while the rest of staking buttons are still available
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188627379)
> 188627379-remove-marinade-stake-button

- app/controllers/api/v1/ping_times_controller.rb
- app/views/public/api_documentation.html.erb
- config/routes.rb
- test/controllers/api/v1/ping_times_controller_test.rb
- add stats to api
- check the new endpoint at /api/v1/ping-time-stats/:network
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188705398)
> 188705398 ping time stats api

- app/models/ping_thing_archive.rb
- app/models/ping_thing_fee_stat_archive.rb
- config/schedule.rb
- db/migrate/20250211081218_add_fee_fields_to_ping_thing_archives.rb
- db/migrate/20250211091212_create_ping_thing_fee_stat_archives.rb
- db/schema.rb
- script/archives/archive_ping_thing_stat.rb
- add fee-related fields to archives
- update schedule
- create test ping things and ping thing fee stats
- run archive scripts (/scripts/archives/archive_ping_thig* )
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188854809)
> 188854809-update-db-fields-for-ping_thing_archive

- app/models/ping_thing.rb
> 188949563-add-regions-to-pt-whitelist

- app/models/stats/vote_account_history.rb
- app/models/vote_account_history.rb
- app/views/vote_accounts/_vote_account_histories_table.html.erb
- test/logic/validator_score_v1_logic_test.rb
- test/models/stats/vote_account_history_test.rb
- test/models/vote_account_history_test.rb
- after applying timely vote credits to solana our vote credit stats should be adjusted to return correct data
- run tests
- check home page - vote credit percent stats shoud be positive
- check vote accounts details pages for random validators - all recent activity data should be positive
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188854473)
> 188854473-fix-vote-credit

- config/deploy.rb
- config/deploy/production.rb
- config/deploy/stage.rb
- Deploy to staging and confirm both sidekiq instances are running
> 188949673 Update sidekiq blockchain configuration

- app/javascript/packs/validators/components/scores.js
- app/javascript/packs/validators/components/validator_score_modal.vue
- app/models/validator.rb
- app/views/public/faq.en.html.erb
- app/views/validators/_scores.html.erb
- adds badges and descriptions for vote latency score
- check the places where score points should be visible - it should include vote latency score (validators list, validator details)
- check faq
- check score modal
- https://www.pivotaltracker.com/story/show/188983161
> add points and descriptions for vote latency scores

- app/views/layouts/application.html.erb
- Removes gosquared 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/189011440)
> Remove gosquared

- app/controllers/api/v1/vote_controller.rb
- app/models/blockchain/block.rb
- app/models/blockchain/transaction.rb
- app/views/public/api_documentation.html.erb
- config/routes.rb
- test/controllers/api/v1/vote_controller_test.rb
- add API for blockchain votes and blocks
- run tests
- validate vote api endpoints and check if all parameters work as expected
- check if documentation is correct
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188931945)
> 188931945 blockchain api

- app/javascript/packs/ping_things/index_template.vue
> sc-163373-fix-typo-on-validators-app

- app/views/validators/_table.html.erb
> sc-163458-add-active-stake-to-data-centers-table

- app/javascript/packs/validators/validator_details.vue
- app/logic/solana_logic.rb
- app/views/validators/_table.html.erb
- Add software client mapping for Paladin
- Run gather and scoring scripts
> 164349 add missing mapping for paladin

- app/logic/solana_logic.rb
> Update software client name and id mapping

- app/models/validator_score_v1.rb
- app/views/public/faq.en.html.erb
- test/models/validator_score_v1_test.rb
> sc-165249-remove-bonus-point-if-validator-s-withdrawer-matches-identity

- app/models/validator.rb
- test/factories/policy_identities.rb
- test/models/validator_test.rb
- run tests
- `rails r script/prune_database_tables.rb` - should work without errors
> sc-167008-fix-nameerror-in-prune-script

- .rubocop.yml
- app/services/update_policies_service.rb
- app/workers/update_image_file_worker.rb
- script/validators_update_avatar_files.rb
> sc-166727-investigate-large-number-of-errors-related-to-avatars

- app/javascript/packs/epochs/epoch_stats_component_template.vue
- chart for epochs history in landing page
- get some epochs if you dont have any 
- see the home page - there should be a new epoch history chart.
- make sure it's displayed properly, has a working tooltips etc
> sc-168008-add-epochs-history-chart

- Gemfile
- Gemfile.lock
> sc-168803-update-ruby-solana-gem-version-in-validators
