brianlong/www.validators.app

app/views/validators/_block_history_chart.html.erb
- Add cluster skipped slot % MA stat back to graph on validator show page
=> Add back cluster moving average

config/schedule.rb
- Change schedule for prune_database_tables script
You can try it on your local machine, but please remember it will affect your crontab
- run `whenever --update-crontab --set environment=production` 
- `crontab -e`, last entry line should start with `0 1 * * *` and include `script/prune_database_tables.rb `
- then please run `whenever --update-crontab --set environment=stage` 
-  `crontab -e`, last entry line should start with `0 13 * * *`  and include `script/prune_database_tables.rb `
- to clear crontab run crontab -r
Also, 
- check `cap production deploy --dry-run`
- check  `cap stage deploy --dry-run`
You should see different `environment` values under `whenever:update_crontab` log entry in terminal
- https://www.pivotaltracker.com/story/show/177711219
- [] Is there appropriate test …
=> 177711219_change_schedule_for_stage

app/logic/validator_score_v1_logic.rb
- Limits score records to last 2 days when counting root and distance stats
- Locally: run daemons. On staging: let it refresh the batch. Compare the difference on homepage in table header.
- https://www.pivotaltracker.com/n/projects/2177859/stories/178742429
=> 178742429 count root and distance stats from last 2 days

app/logic/validator_score_v1_logic.rb, app/models/validator_score_v1.rb, app/services/validator_software_version.rb, test/models/validator_score_v1_test.rb
scores for validators software versions should be given correctly
while running scripts filter validators by specific versions and check if the scores are right:
- if version is >= current_version (marked green on the bottom of homepage) - 2 pts
- if version is < current_version, but only by minor - 1pts
- if version is < current_version or nil - 0pts
https://www.pivotaltracker.com/story/show/178912445
=> 178912445-fix-software-version-score

app/controllers/validators_controller.rb, app/models/validator_block_history.rb, test/models/validator_block_history_test.rb
- Add relationship between batch and validator_block_history
- Change way of getting data for average
- Part 2/2, first merge and run script from https://github.com/brianlong/www.validators.app/pull/182
- Open show page for any validator
- check Skipped Slot History table (best way to check it is to run first master, see the table, then switch to this branch and check if the results has not been changed)
- https://www.pivotaltracker.com/story/show/178998318
=> 178998318_add_average_to_batches_controller_changes_2

app/logic/report_logic.rb, app/views/validators/_software_versions.html.erb, dev/report_software_version_demo.rb
only scorable validators should be included in software_versions table 
- there's a script to create software_version_report inside /dev folder. Run it and check for errors.
- open links in software versions table and see if count from the table matches number of validators displayed
- if there are any inactive validators, they should not be included in the count
https://www.pivotaltracker.com/story/show/179042697
=> 179042697-audit-software-scores-table

app/controllers/validators_controller.rb
- Use safe operator when looking for skipped_slot_all_average + going to next record when result is nil
- Choose one of the validator
- Remove batch connected with one of the validator_block_history
- Remove limit from line 91 from validators_controller
- Open browser on show view for this validator
- Check if the charts are unchanged
- https://www.pivotaltracker.com/story/show/179166834
=> 179166834_undefined_method_skipped_slot_average

app/views/validators/_no_search_results.html.erb, app/views/validators/_search_bar.html.erb, app/views/validators/_sort_bar.erb
- Add search bar to results not found
- Add search phrase to search input
- Make search input required to not search for empty phrase
- Type phrase to input and click search button
- You should see phrase in the input
- Type phrase that gives you no results to see search input on no results page
- https://www.pivotaltracker.com/story/show/179268257
=> 179268257_add_search_bar_to_results_not_found

app/views/cluster_stats/_root_distance.html.erb, app/views/cluster_stats/_skipped_slot.html.erb, app/views/cluster_stats/_skipped_vote.html.erb, app/views/cluster_stats/_vote_distance.html.erb, app/views/cluster_stats/index.html.erb
- Put Root Distance, Vote Dist, Skipped Vote and Skipped Slots stats before "Top Validators by" block.
- add percents to stats
see applied changes in cluster stats view
- https://www.pivotaltracker.com/story/show/180047388
=> 180047388-tweak-cluster-stats-page

daemons/gather_vote_account_details_daemon.rb
- withdraw-authority-score should be working on testnet
- run gather_vote_account_details_daemon.rb ( you can reverse order of networks at the top )
and see if there are no errors. 
https://www.pivotaltracker.com/story/show/180343870
=> 180343870-fix-withdraw-authority-score

app/models/validator.rb, app/services/validator_check_active_service.rb, db/migrate/20211220084849_add_is_destroyed_to_validators.rb, db/schema.rb, test/services/validator_check_active_service_test.rb
- mark validators that are no longer in solana as destroyed
- run tests
- try to run `ValidatorCheckActiveService.new.update_validator_activity` in rails console after running daemons for a while, although it's not certain that there will be any marked
- already tested on stage and there are some validators marked 
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180640347)
=> 180640347 mark removed validators

app/logic/stake_logic.rb, app/models/stake_account.rb, app/queries/stake_account_query.rb, test/queries/stake_account_query_test.rb
- active stake should not be displayed and should not be counted for stake pool averages
- check /stake_accounts page and check if there are any accounts with 0 stake
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180873430)
=> 180873430 hide stake accounts with no stake

app/models/validator.rb, app/services/validator_check_active_service.rb, test/services/validator_check_active_service_test.rb
- If validator is marked as destroyed, it should be unmarked when it is active again
- 
- run tests
- set any validators is_destroyed to true and run ValidatorCheckActiveWorker
- is_destroyed for this validator should go back to false
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/180932001)
=> 180932001-reset-is_destroyed-when-necessery

app/javascript/packs/stake_accounts/pool_stats.js
- tweak displaying 0 stake pool values
- Go to localhost:3000/stake-pools, choose ie. jpool, values in statistics should be 0 not 'N / A'
- https://www.pivotaltracker.com/story/show/180903060
=> 180903060_tweak_displaying_0_stake_pool_values

app/javascript/packs/stake_accounts/stake_account_row.js
- For stake smaller than 0.5 SOL do not round to 0, but display "<0.5"
- Check an account with small stake (eg. stake account 7DBSpxcymkAjkFjLF9hcw7MNtfzSSD6KuDDFuy6BKh4b or account 5C8xyL5ESXv6PqJexW5RATEBgLKvcVR3dEHxhmLSEkaZ) before and after change indroduced in this PR. The stake should no longer be displayed as "0"
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180887252)
=> Tweak displaying small stake

app/assets/stylesheets/tables.scss, app/controllers/api/v1/stake_accounts_controller.rb, app/controllers/api/v1/stake_pools_controller.rb, app/javascript/packs/stake_accounts/index.js, app/javascript/packs/stake_accounts/index_template.vue, app/javascript/packs/stake_accounts/pool_stats.js, app/javascript/packs/stake_accounts/pools_overview.js, app/javascript/packs/stake_accounts/stake_account_row.js, app/models/stake_pool.rb, app/views/api/v1/stake_pools/index.json.jbuilder, test/controllers/api/v1/stake_accounts_controller_test.rb, test/controllers/api/v1/stake_pools_controller_test.rb, test/models/stake_pool_test.rb
- If no pool is selected - display pools overview.
- Load /stake-pools in the browser and review
- Select a pool by clicking on logo - make sure overview was replaced by selected pool stats. Do the same for other pools
- Click on 'reset filters' and make sure that overview is displayed again
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180991233)
=> 180991233 add pools overview

app/controllers/api/v1/api_controller.rb, app/javascript/packs/stake_accounts/validator_row.js, app/models/validator.rb, app/models/validator_score_v1.rb, app/views/validators/_scores.html.erb, test/controllers/api/v1/api_controller_test.rb, test/models/validator_score_v1_test.rb
- If score is 0 because validator is private or has admin_warning, display 'N/A' in views. Keep 0 in db.
- Review on homepage, validator details page and stake pools page.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181049608)
=> 181049608 do not display zero scores

app/logic/solana_logic.rb
- Use dig only on hash
- Run tests
- Run `rails r script/validators_get_info.rb` you should see no errors
- https://www.pivotaltracker.com/story/show/181111995
=> 181114658_error_in_invalid_configs

app/logic/stake_logic.rb, test/logic/stake_logic_empty_responses_test.rb, test/logic/stake_logic_test.rb
- If there is no response with stake_accounts from solana, nothing should be deleted.
- run tests
- try to run dev/stake_logic_demo.rb with changed urls and see if the behavior is correct
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181111955)
=> 181111955 rescue from no stake accounts

app/javascript/packs/stake_accounts/pool_stats.js
Change link to metrics explanation to link to delegation strategy in stake pool stats
- Adds links to delegation strategy to stake pools
- Go to /stake-pools
- Filter by each stake pool to see stats
- You should see the link under the name of the stake pool "See delegation strategy" - check it for every validator
- https://www.pivotaltracker.com/story/show/181071554
=>  181071554_add_link_to_delegation_strategy

app/controllers/api/v1/ping_things_controller.rb, app/controllers/ping_things_controller.rb, app/models/ping_thing.rb, app/views/ping_things/index.html.erb, app/views/public/api_documentation.html.erb, db/migrate/20220224142533_fix_index_on_reported_at_to_ping_thing.rb, db/schema.rb, test/controllers/api/v1/ping_thing_controller_test.rb, test/factories/ping_things.rb
- Uses reported_at instead of created_at
- Review in browser under localhost:3000/ping-thing or on staging
- Try fetching more than one ping by API and confirm that they're sorted by reported_at
eg. pull by ```curl -H "Token: YOUR-KEY" 'https://stage.validators.app/api/v1/ping-thing/mainnet?limit=5```
and compare results with: https://stage.validators.app/ping-thing
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/181341014)
=> 181341014 sort pings by reported at

app/views/public/api_documentation.html.erb, config/routes.rb, test/controllers/api/v1/validator_block_histories_controller_test.rb
- change underscores to dashes in validator_block_history_path
- run tests
- check if `/api/v1/validator-block-history` endpoint works correctly
- check if the old path works as well
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/181656771)
=> 181656771 validator block history new path

app/controllers/validators_controller.rb
- Fixes query that takes wrong batch of validator histories for charts
- Review validator details pages and confirm that charts are fixed now, eg. https://stage.validators.app/validators/1aine15iEqZxYySNwcHtQFt4Sgc75cbEi9wks8YgNCa?locale=en&network=mainnet&order=&refresh=
vs: https://www.validators.app/validators/1aine15iEqZxYySNwcHtQFt4Sgc75cbEi9wks8YgNCa?locale=en&network=mainnet&order=&refresh=
- Confirm that query is still quick
-
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/182012799) …
=> 182012799 fix query on validator details

app/javascript/packs/ping_thing/bubble_chart.js, app/javascript/packs/ping_thing/ping_thing_header.vue, app/javascript/packs/ping_thing/stats_chart.js
- remove 60 sec limit on ping thing charts
- create ping thing with response_time greater than 60 sec and see if it's properly displayed on chart
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182297936)
=> 182297936-update-max-in-ping-thing-charts

app/queries/validator_query.rb, test/queries/validator_query_test.rb
- secondary sort order in validators list should be random
- try sorting by score and refresh page multiple times. score order should always be descending, but secondary order should be random
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182565319)
=> 182565319-fix-random-sorting

app/services/validator_check_active_service.rb
- If validator does not have validator history mark it inactive and destroyed
- Run tests
- Create local validator with `is_active: true` and `is_destroyed: false`, run `ValidatorCheckActiveService.new.update_validator_activity` - it should set `is_active` to false and `is_destroyed` to true
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182619709)
=> 182619709_review_deactivation_script

test/models/validator_history_test.rb
- Specify validator history by account not index number in test
- Check if the error still occurs in CI runs
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182803413)
=> 182803413_review_failing_test

app/services/gatherers/vote_account_details_service.rb, dev/gather_vote_account_details_force_update.rb
- determine why some validators does not have authorized_withdrawer_score updated
- add always_update flag to the VoteAccountDetailsService so it can be run manually and update score for each validator
- run dev/gather_vote_account_details_force_update.rb
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182809739)
=> add always_update option to VoteAccountDetailsService

app/javascript/packs/stake_accounts/index_template.vue
- tables on stake pools page should not load twice
- go to /stake-pools
- try changing pool, pagination
- tables should load only once
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183139282)
=> 183139282 fix flickering stake pool

app/javascript/packs/ping_thing/stats_chart.js, app/models/ping_thing_stat.rb, app/services/create_ping_thing_stats_service.rb, db/migrate/20220919072658_add_slot_latency_to_ping_thing_stats.rb, db/schema.rb, dev/create_test_ping_things.rb, test/services/create_ping_thing_stats_service_test.rb
- add slot latency to ping_thing_stats and display it in the chart
- run tests
- populate db with test data
- check if ping thing stats have average_slot_latency populated
- check if additional data is visible on the chart (as in pt story)
- https://www.pivotaltracker.com/story/show/183298708
=> 183298708 add slot latency to pt stats

app/javascript/packs/ping_thing/stats_bar.vue, app/javascript/packs/ping_thing/stats_chart.js, app/models/ping_thing.rb, app/models/ping_thing_recent_stat.rb, db/migrate/20220922145718_add_average_slot_latency_to_ping_thing_recent_stats.rb, db/schema.rb, dev/create_test_ping_things.rb, test/models/ping_thing_recent_stat_test.rb
- Include average slot latency in recent stats table for 5min and 60 min
- run tests
- `rails r dev/create_test_ping_things.rb`
- run worker PingThingRecentStatsWorker
- look at the table with pt stats on the landing page and in /ping-thing site and confirm that everything looks ok
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183338373)
=> 183338373 average latency in recent stats

app/javascript/packs/ping_thing/stats_bar.vue, app/views/public/api_documentation.html.erb
- Fixes stats table icon and layout
- Review in browser on home page 
(you can generate pings first, but it's not necessary:
`rails r dev/create_test_ping_things.rb` & `rails r script/one_time_scripts/back_fill_ping_thing_stats.rb` - sidekiq must be running)
- Test on desktop and mobile
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183374980)
=> 183374980 fix recent stats table display

script/validator_ips/remove_without_validator_or_gossip_node.rb
Add script for removing orphaned validator_ips (no validator or gossip_node)
- Removes orphaned validator ips
- Run script
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183323571)
=> 183323571_remove_validators_ips_without_val_or_gossip_node_assigned

app/assets/stylesheets/tables.scss, app/helpers/validators_helper.rb, app/javascript/packs/stake_accounts/charts/root_distance_chart.js, app/javascript/packs/stake_accounts/charts/skipped_slot_chart.js, app/javascript/packs/stake_accounts/charts/skipped_vote_speedometer.js, app/javascript/packs/stake_accounts/charts/vote_distance_chart.js, app/javascript/packs/stake_accounts/stake_account_row.js, app/javascript/packs/stake_accounts/validator_row.js, app/views/validators/_table.html.erb
- Moves max chart value to the right place above the charts
- Generate data for the charts (gather_rpc and validator_score daemons)
- Go to the main page, find a chart with max value larger than 20 and confirm that max value is displayed in the right place (see screenshot in PT story)
- Generate data for stake pools (see ## STAKE POOLS section in db instructions)
- Check the same on stake pools page (localhost:3000/stake-pools)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183370357) …
=> 183370357 fix chart annotations

app/logic/gossip_node_logic.rb, app/models/gossip_node.rb, app/queries/gossip_node_query.rb, db/migrate/20221005162534_add_is_active_to_gossip_node.rb, db/schema.rb, script/update_gossip_nodes.rb, test/controllers/api/v1/gossip_nodes_controller_test.rb, test/factories/gossip_nodes.rb, test/logic/gossip_node_logic_test.rb, test/models/gossip_node_test.rb
- Adds is_active attribute to gossip nodes
- Run migration
- Confirm the script runs without any errors: `rails r script/update_gossip_nodes.rb`
- If you had some gossip nodes already in your db, then those which don't exist anymore should become inactive (check the number in console `GossipNode.where(is_active: false).count`)
- If you didn't have any gossip nodes in your local db, then all new nodes should be active (confirm in console `GossipNode.where(is_active: false).count` - should be 0)
- Use API to get gossip nodes: https://stage.validators.app/api-documentation?locale=en&network=mainnet#gossip-nodes. Confirm that the output no longer includes inactive gossip nodes.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183466933)
- [] Is …
=> 183466933 add gossip node status

app/controllers/api/v1/data_centers_controller.rb, app/javascript/packs/validators/validators_map.vue, app/javascript/packs/validators/validators_map_data_center_details.js, app/models/data_center_stat.rb, app/services/data_centers/fill_data_center_stats.rb, db/migrate/20221011131406_add_active_validators_count_to_data_center_stats.rb, db/schema.rb, test/controllers/api/v1/data_centers_controller_test.rb, test/factories/data_center_stats.rb, test/services/data_centers/fill_data_center_stats_test.rb
- Updates data center stats
- Run migrations, run sidekiq
- Generate some validators and nodes if you don't have any (gather daemon + update gossip nodes script)
- Generate some IPs and data centers if you don't fave any (`rails r script/data_centers_scripts/append_data_centers_geo_data.rb`)
- Update data center stats: `rails runner "DataCenterStatsWorker.perform_async('mainnet')"` and `rails runner "DataCenterStatsWorker.perform_async('testnet')"`
- Check your DataCenterStat through console, you should see 2 fields populated with some values: validators_count and active_validators_count; same for nodes: gossip_nodes_count and active_gossip_nodes_count
- You can try to manually deactivate one of validators or nodes assigned to your data centers (update is_active: false), and then run …
=> 183466948 update data center stats

config/deploy.rb
Add front daemon to capistrano deploy config.
Should be tested on stage. The front daemon is utilized for gathering the SOL price at homepage.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183532155)
=> 183532155 - add front_stats_update to capistrano deploy config

app/javascript/packs/validators/circulating_supply.vue, daemons/validator_score_testnet_v1_daemon.rb
PR adds the activeStakeWorker to daemon for testnet. Also it fixes the update on the homepage.
Make sure to have daemons running: 
daemons/validator_score_testnet_v1_daemon.rb
daemons/front_stats_update_daemon.rb
Verify the active stake values for testnet. You can manually change the last of ClusterStat in db (its total_active_stake attribute).
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183590725)
=> 183590725 - add stake worker to testnet

app/logic/report_logic.rb, app/services/create_cluster_stats_service.rb, test/controllers/cluster_stats_controller_test.rb, test/services/create_cluster_stats_service_test.rb
PR removes the cluster stats model attributes from the report logic.
* run tests
* verify if skipped and distance components on the homepage update with correct data
* investigate the report_cluster_stats, if it contains duplicated data
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183637326)
=> 183637326 - remove cluster stats model attrs from the report

app/assets/stylesheets/map.scss, app/controllers/api/v1/data_centers_controller.rb
- Fixes an error with duplicated keys
- It's difficult to reproduce this error locally. I would advise to test it on staging, and compare with production version.
- Error description: on production there's no bubble for Germany (that's because 'DE' key is already taken by Delaware, US). After deploy to staging, this problem should be resolved, and you should be able to see a bubble for Germany. 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/183640495)
=> 183640495 fix error with duplicated keys for a map

config/deploy.rb, daemons/concerns/leader_stats_helper.rb, daemons/front_stats_update_daemon.rb, daemons/leader_stats_update.service, daemons/leader_stats_update_daemon.rb
PR reduces the interval for fetching data of leaders component.
* restart the `daemons/front_stats_update_daemon.rb`
* run the `daemons/leader_stats_update_daemon.rb`
Verify if the homepage is updated correctly and includes a valid data.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183639579)
=> 183639579 - reduce leader component intervals

app/javascript/packs/leaders/leaders_stats_component_template.vue, daemons/concerns/leader_stats_helper.rb, daemons/leader_stats_update_daemon.rb, test/daemons/leader_stats_helper_test.rb, test/vcr_cassettes/daemons/leader_stats_helper_test/test__all_leaders_returns_data_for_both_networks.yml, test/vcr_cassettes/daemons/leader_stats_helper_test/test__leaders_for_network_returns_correct_leaders.yml
- Fixes current leader component: 
- tweaks query to pull only needed data, 
- fixes query to use existing indexes,
- fixes results order to match leaders order in schedule
- Locally: run `rails r daemons/leader_stats_update_daemon.rb` and confirm that leaders visible in leaders component on /home-new are processed one by one, not mixed anymore
- On staging: go to https://stage.validators.app/home-new and check leaders component
-[ URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183651841)
=> 183651841 Fix current leader component

config/initializers/devise.rb
PR changes the devise session timeout value from default (30 minutes) to 24 hours.
Devise gem is covered by tests. Another way to find out if the session timeout is valid is simply log in and verify after 24 hours whether the user is still signed in.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182475277)
=> 182475277 - extend session time to 24 hours

app/queries/commission_history_query.rb, test/queries/commission_history_query_test.rb
Increase time range for commission histories view. 
Enter the /commission-changes page and check if the results date range is within 60 days.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183654712)
=> 183654712 - increase the time range ago in commission history view

app/javascript/packs/validators/validators_map.vue
- do not display leaders with 0-unknown data center on a map
- check the map - perhaps on staging it should be possible to wait for a leader with unknown dc - it should not be displayed on a map
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183749738)
=> 183749738-handle-unknown-dc-on-leader-map

app/services/solana_rpc_client.rb, config/initializers/solana_networks.rb, daemons/gather_vote_account_details_daemon.rb, dev/gather_vote_account_details_force_update.rb, script/gather_stake_accounts.rb, script/one_time_scripts/reduce_validators_with_invalid_config.rb, script/update_gossip_nodes.rb, script/validators_get_info.rb
PR adds pythnet in to the gather vote account details daemon.
- ticket explicitly concerns the rake task - `daemons/gather_vote_account_details_daemon.rb` so please execute it and check for pythnet's vote account details.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183730419)
=> 183730419 - add pythnet to gather vote daemon

app/models/commission_history.rb, app/services/create_commission_history_service.rb, test/mailers/commission_history_mailer_test.rb, test/models/commission_history_test.rb
PR fixes error regarding CommissionHistory no found. It makes sending a CommissionHistoryMailer after the CommissionHistory is created.
It would be hard to replicate the AppSignal issue. Before changes the CommissionHistory hasn't been created (transaction commited) before the CommissionHistoryMailer was executed. Hereby that the "Couldn't find CommissionHistory" was been raising.
You can test `CreateCommissionHistoryService` by the following:
- look for `ValidatorScoreV1` record with `validator.watchers` included.
- run `#{validator_score_v1}.create_commission_history`
Console output should include `ActionMailer::MailDeliveryJob` result. 
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183888702)
- [] Did I take into …
=> 183888702 - perform notify_users after commission history was saved

app/views/layouts/_footer.html.erb
Unfortunately we cannot load vue components on real `turbolinks:load` events. These components are being loaded on `DOMContentLoaded` event instead. 
Notice: if turbolinks data is disabled (at our homepage e.g.) then turbolinks reloads all data, so the events `turbolinks:load` and `DOMContentLoaded` do perform at the same point.
This PR only turns on turbolinks on Sol Prices page.
- check sol prices page if the content is loaded
- at Sol Prices page move to page where turbolinks are activated
- click "back button" and check whether the `<body>` tag has only been changed (`<head>` should stay untouched)
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183882661)
- [] Did I take into consideration possible security …
=> 183882661 - enable turbolinks on sol prices page

app/javascript/packs/validators/circulating_supply.vue
- Do not refresh total and circulating supply via web3
- go to the home page and check if Stake component works properly
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184073409)
=> 184073409-no-refresh-for-supply-stats

app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb
PR fixes navigation to validators from any not-turbolinked page (such as home).
Check if current page is being reloaded before user redirects another page (e.g. clicks Validators link at home page).
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184072139)
=> 184072139 - remove turbolinks for validators

app/javascript/packs/validators/validator_details.vue
- Fixes the issue described in PT story
- Test on the examples that contain slash in  DC name, eg. https://stage.validators.app/validators/4DBSKsjbs66piUiQ6dUjw6cdVzAGc4FgeWSZ5UVPY5kr?locale=en&network=mainnet, https://stage.validators.app/validators/E6cyDdEH8fiyCTusmWcZVhapAvvp2LK24zMLg4KrrAkt?locale=en&network=mainnet
- Other validators with the same problem: https://stage.validators.app/data-centers/35598-RU-Europe-slash-Moscow?locale=en&network=testnet
- Click through several of them
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184204098)
- [N] Does this PR have any …
=> 184204098 fix link to data center

app/assets/stylesheets/images.scss, app/javascript/packs/validators/validator_details.vue
- Adds loading image to validator details page
- Test on staging - go to validator details page through a link on homepage, on data centers page etc.
- If you want to test locally, you might need to add some timeout to be able to see the difference. Replace the following line `ctx.is_loading_validator = false` in validator_details.vue with:
```
setTimeout(() => {
ctx.is_loading_validator = false
}, "3000")
```
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184214120)
=> Add loading image to validator details, charts and table

app/controllers/asns_controller.rb, app/controllers/data_centers_controller.rb, app/services/sorted_data_centers.rb, test/services/sorted_data_centers_test.rb
- exclude inactive validators from data_center query
- run tests
- check index page of ASN/Data Centers - only active validators should be in the numbers
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184376335)
=> 184376335-filter-data-centers-by-inactive

app/models/epoch_wall_clock.rb, app/services/track_commission_changes_service.rb
- use only active validators for commission tracking
- Verify the following scenarios on staging:
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184339573)
=> 184339573-active-validators-commission-tracking

app/javascript/packs/ping_things/ping_thing_table.vue
PR applies minor change regarding url pointing out to solana explorer.
- locally you can create recent ping things via `ruby dev/create_test_ping_things.rb`
- verify if the links within Ping Thing site points out to the explorer solana.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184531484)
=> 184531484 - change link from solana beach to explorer solana

app/logic/stake_logic.rb, app/models/validator.rb, test/logic/stake_logic_test.rb
- average score for stake pools are stake-weighted
- run tests
- if you can, try to run `rails r script/gather_stake_accounts.rb` and see if the average scores are different than before
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184297117)
=> 184297117-stake-weight-scores

app/queries/validator_search_query.rb, test/queries/validator_search_query_test.rb
- Enables widlcard search for validator name, leaves other search fields as-is
- Go to validator search and type any part of validator name - this should return results as on attached screenshot
- Try do the same with other fields - eg. copy validator identity and truncate few characters from the beginning - this should not work. As in story description, we want to support widcard search only for validator name
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184655857)
=> 184655857 - Enable wildcard search for validator name

daemons/process_ping_thing_daemon.rb
- sleep should not occur if there are any ping_thing_raws to process
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184670705)
=> 184670705-remove-pt-daemon-sleep-time

script/remove_unconfirmed_users.rb
PR fixes the remove_unconfirmed_users script.
- `rails test`
- on staging:
- - count the User records and check how many users are affected `User.where("created_at < ?", User::CONFIRMATION_TIME.ago).where(confirmed_at: nil)`
- - create another unconfirmed user e.g. `User.create(email: "testuser@test.com", password: "password", username: "test.user", created_at: 10.days.ago)`
- - run the script `script/remove_unconfirmed_users.rb`
- - verify the `remove_unconfirmed_users.rb.log`
- - check if the invalid users have been destroyed.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184689406)
- [] Was every important …
=> 184689406 - add the environment to script

app/api_clients/coin_gecko_client.rb, daemons/front_stats_update_daemon.rb
- avoid blocking front stats broadcast if solana prices does not load
- run `rails r daemons/front_stats_update_daemon.rb`
- check if sol prices update every minute
- check if rest of the stats loads fast
=> 184810886-fix-coingecko-broadcast

app/logic/sol_prices/coin_gecko_logic.rb
- retry getting prices from coingecko when values are empty
- test `rails r script/sol_prices/coin_gecko_gather_yesterday_prices.rb`
- run tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184823090)
=> 184823090 fix missing sol prices

app/helpers/stake_pools_helper.rb, app/views/validators/_table.html.erb
- icons of stake pools should display pool names on hover
- should be linked to stake pool page
- check validators index - icons should work as described above
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184873312)
=> 184873312-descriptions-for-stake-pool-logos

app/helpers/validators_helper.rb, app/javascript/packs/validators/validator_row.js, app/models/validator.rb, test/helpers/validators_helper_test.rb, test/models/validator_test.rb
- Removes `lido?` and `is_validator_lido` methods and related code
- There are no private lido validators anymore (if they're staking some private validators, they should be displayed in the same way as all private validators). So just confirm that other private validators are still correctly displayed in the tables ("Private Validator" instead of name, no commission displayed, as on the screenshot below), both on homepage and stake pools page
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184941141) …
=> 184941141 Remove excepions for lido

app/assets/stylesheets/tables.scss, app/views/validators/_table.html.erb
- Fixes validator name alignment
- See the screenshot attached to PT story. The problem occurs on data center details page, and for logged in users. So log in to your account, go to some DC page, reduce window size until avatars disappear and confirm that validator name is displayed without padding on the left. Log out and confirm it's still correct.
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184986979)
=> 184986979 fix validator name alignment

app/logic/solana_logic.rb
If db connection has been lost exit from daemon.
You can manually add `raise ActiveRecord::ConnectionNotEstablished` in `solana_logic.rb` within the logic inside and check if the script has been closed.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185080194)
=> 185080194 - add rescues from lost db connection

app/javascript/packs/navigations/validator_searcher_btn_template.vue
- Adds focus to search field in top menu
- Use searcher in page top menu and confirm that you can type after toggling the search field (without an additional click inside input area)
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184207370)
=> 184207370 add focus to search field

app/models/vote_account.rb, script/one_time_scripts/remove_invalid_authorized_voters.rb, test/models/vote_account_test.rb
PR applies changes to callback logic for authorized_voters. New AccountAuthorityHistory record should be created if authorized_voters hash values have changed. New one time script will remove invalid authorized voters histories.
- execute `rails r script/one_time_scripts/remove_invalid_authorized_voters.rb` and look for any errors
- vote accounts should have most recent authorized_voters value (from latest history)
- verify via console if there are repeated values of authorized_voters hash within each VoteAccount record. If so then the script has failed.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185302616)
- [] …
=> 185302616 - fix saving Authorized Voters change

app/javascript/packs/account_authority_histories/index_template.vue, app/queries/account_authority_query.rb, test/queries/account_authority_query_test.rb
- authority changes with no real changes should not be displayed
- check authorities changes listed under vote_account details - those with nil before values or with no real changes should not be displayed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185454134)
=> 185454134 hide authority changes with nil before

app/controllers/application_controller.rb, test/controllers/public_controller_test.rb
- set default network during incoming requests if param is missing or is incorrect.
- `rails test`
- enter any page and check scenarios
- - when network param is missing( mainnet should be rendered)
- - when network param passed in is valid( intendent network should be rendered)
- - network is invalid( mainnet should be rendered)
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185636809)
=> 185636809 - redirect mainnet if incorrect network

.github/workflows/test_suite.yml
- As in the title.
- Check for any deprecated warnings in github actions output.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185697075)
=> 185697075 - remove deprecated set-output in github actions

app/assets/stylesheets/images.scss, app/javascript/packs/validators/validator_details.vue, app/views/validators/_table.html.erb
- Moves jito logo away from validator logo
- Test validator index and details pages in all 3 scenarios:
- validator with stake pools and jito
- validator with only stake pools or only jito
- validator without stake pools and that is not jito
and confirm that logos are correctly displayed in all cases
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/185838494)
=> 185838494 move jito badge

app/services/gatherers/vote_account_details_service.rb, script/validators_get_avatar_url.rb
- Fixes the error in gather_vote_accounts daemon for validators without scores
The problem is that the daemon is raising error for validators that don't have a score, and as a result daemon is restarted, starts processing from the beginning (mainnet) and never reaches testnet.
```
Oct 02 12:53:36 background.validators.app gather_vote_account_details_daemon[1887703]: NoMethodError
Oct 02 12:53:36 background.validators.app gather_vote_account_details_daemon[1887703]: undefined method `authorized_withdrawer_score=' for nil:NilClass
```
- Sends unexpected errors to Appsignal 
- Run `rails r daemons/gather_vote_account_details_daemon.rb` (you can edit line 9 to run for only one network) and confirm that it doesn't break. 
- On staging: wait until the gather script processes all networks and …
=> 186156556 handle errors in vote accounts daemon

app/models/explorer_stake_account.rb, script/prune_database_tables.rb
- remove audits after 60 days
- exclude created_at, updated_at, epoch from being audited
- run `rails r script/gather_stake_accounts.rb` and then `rails r script/gather_explorer_stake_accounts.rb`
- run `rails r script/prune_database_tables.rb`
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186133556)
=> 186133556-set-audits-retention-time

app/models/vote_account.rb, config/sidekiq.yml.example
- Moves CheckGroupValidatorAssignmentWorker to low priority queue
- Run sidekiq
- Run daemons/gather_vote_account_details_daemon.rb and confirm that workers are added to low_priority queue
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186181863)
=> 186181863 move group workers to separate queue

app/models/vote_account.rb, script/prune_database_tables.rb
- add lacking dependent: destroy to avoid foreign key constraint failure
- find validator with account_authority_histories
- set validator created_at older than 60 days
- remove all vote account histories for it and set active stake to 0
- run `rails r script/prune_database_tables.rb` and check if validator has been deleted without errors
=> 186183228-fix-prune-db-script

app/models/vote_account.rb, test/models/vote_account_test.rb
- changes of epoch only does not run check_group_assignment in vote accounts
- run tests
- check on staging
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186181102)
=> 186181102-fix-condition-for-check-group-assignment

app/controllers/validators_controller.rb, app/queries/validator_query.rb
- Fixes an error with displaying inactive validators described in PT story
- Confirm that inactive validators are not displayed anymore
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186655228)
=> 186655228-fix-displaying-validator-list

app/controllers/concerns/stake_accounts_controller_helper.rb, app/controllers/explorer_stake_accounts_controller.rb, app/queries/explorer_stake_account_query.rb, test/controllers/explorer_stake_accounts_controller_test.rb, test/queries/explorer_stake_account_query_test.rb
- Adds top 20 stake accounts ordered by delegated stake.
- make sure you have db populated with explorer stake accounts
- at stake explorer page when filters are reseted (filters are blank) the table should include only 20 of top stake accounts records ordered by stake
- enter some values to the filters and check if that works as usual (the output should be paginated)
- if both filters and stake accounts are absent then the page should include content "Use the filters above to see Stake Accounts."
- if filters are presented, but stake accounts are missing for the criteria then there should an information "No results for given criteria." included.
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186486202)
- [] Did I …
=> 186486202 - add top records in explorer stake account page

app/javascript/packs/mixins/validators_mixins.js, app/javascript/packs/validators/validator_details.vue, app/models/validator.rb, app/queries/validator_query.rb, app/views/validators/_table.html.erb, test/models/validator_test.rb, test/queries/validator_query_test.rb
- Displays jito badge only if jito commission is below maximum
- Updates jito filter to only return validators with commission below maximum
- Always displays jito commission for jito validators
- Use "jito" filter on home page, and confirm that validators with high jito commission are not returned (eg. Shinobi -  Ninja1spj6n9t5hVYgF3PdnYz2PLnkt7rvaw3firmjs)
- Confirm that jito badge is not displayed
- Confirm that jito commission on details page is still displayed
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186775243)
- [N] Does …
=> 186775243 update jito logic

app/javascript/packs/validators/charts/skipped_after_chart.js, app/logic/validator_score_v1_logic.rb, app/models/validator_block_history.rb, app/models/validator_score_v1.rb, app/views/validators/_table.html.erb, app/views/validators/_validator_skipped_slots_chart.html.erb, db/migrate/20240112091915_add_skipped_after_percent_moving_average_to_validator_block_histories.rb, db/migrate/20240112111301_add_skipped_after_moving_average_history_to_validator_score_v1.rb, db/schema.rb, test/controllers/api/v1/validators_controller_test.rb, test/models/validator_block_history_test.rb
- add moving average for skipped after
- run tests
- run gather and score daemons
- check if skipped_after_moving_average is present in validator_block_histories
- check if skipped_after_moving_average_history is present in scores
- check if charts are valid in validator index and other pages
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186818750)
=> 186818750 moving average for skipped after

app/logic/solana_logic.rb, app/models/validator.rb, script/one_time_scripts/remove_validator.rb, test/logic/solana_logic_test.rb, test/scripts/remove_validator_test.rb
- Modifies logic saving validator during CLI Solana request (#validators_info_save)
- `rails test`
1)
- find a validator with network 'testnet' and account '2eCPrXeWo9Cg79cK6eyJdaCoiMDKJMPq7sAhXSP3spQk'. Change its attribute (e.g. name, keybase_id, www_url) and save it.
- run `rails r script/validators_get_info.rb`
- check if the validator attributes are valid (current name is "Edgevana Validator")
2)
- run rails console and remove the validator (account: '2eCPrXeWo9Cg79cK6eyJdaCoiMDKJMPq7sAhXSP3spQk')
- run `rails r script/validators_get_info.rb` again
- in rails console try to find the validator ('2eCPrXeWo9Cg79cK6eyJdaCoiMDKJMPq7sAhXSP3spQk'). It should not exist.
3)
- create a validator with relations assigned
```
validator_histories
validator_block_histories
vote_accounts …
```
=> 186811096 - remove old validator

app/controllers/api/v1/ping_thing_user_stats_controller.rb, app/javascript/packs/ping_things/stats_bar.vue, app/javascript/packs/ping_things/user_stats.vue, app/models/ping_thing.rb, app/services/ping_thing_user_stats_service.rb, dev/create_test_ping_things.rb, test/models/ping_thing_recent_stat_test.rb, test/services/ping_thing_user_stats_service_test.rb
- Sort user ping stats by latency for 5 minutes
- Replaces latency average with median
- On staging:
- run `RAILS_ENV=stage bundle exec rails r dev/create_test_ping_things.rb` (you can run multiple times)
and review https://stage.validators.app/ping-thing page
- Locally:
- run sidekiq
- populate db with `rails r dev/create_test_ping_things.rb`  (you can run multiple times)
- and then create stats: 
`rails r "PingThingUserStatsWorker.perform_async('mainnet')"`
- check stats - should be sorted: …
=> 187184054 sort user ping stats

app/models/ping_thing_recent_stat.rb, app/services/ping_thing_user_stats_service.rb, test/models/ping_thing_recent_stat_test.rb, test/services/ping_thing_user_stats_service_test.rb
- Fixes p90 calculation 
- turn on sidekiq
- run `rails r dev/create_test_ping_things.rb` a couple of times 
- review /ping-thing page and confirm that min, median and p90 looks correct (both general and per user stats) and you no longer see the error described in PT
- correct output should look like below: 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187257572)
=> 187257572 fix p90

app/javascript/packs/ping_things/stats_bar.vue, app/javascript/packs/ping_things/user_stats.vue, app/models/ping_thing.rb, test/services/ping_thing_user_stats_service_test.rb
- Tweaks 0 latencies
- Populate db with some stats records:
```
PingThingUserStat.create average_slot_latency: 6.0, interval: 60, min: 999.0, max: 5342.0, median: 1935.0, p90: 2663.0, num_of_records: 50, network: "mainnet", user_id: User.first.id, username: User.first.username_count: 0, min_slot_latency: 0, p90_slot_latency: 16
PingThingUserStat.create average_slot_latency: 3.0, interval: 60, min: 1003.0, max: 4233.0, median: 2633.0, p90: 4233.0, num_of_records: 21, network: "mainnet", user_id: User.second.id, username: User.second.username, fails_count: 0, min_slot_latency: 0, p90_slot_latency: 6
PingThingUserStat.create average_slot_latency: 0, interval: 5, min: 1114.0, max: 4233.0, median: 1998.0, p90: 4233.0, num_of_records: 7, network: "mainnet", user_id: User.second.id, username: …
```
=> 187277433 fix latency stats

app/models/ping_thing_recent_stat.rb, app/services/ping_thing_user_stats_service.rb, dev/create_test_ping_things.rb, test/models/ping_thing_recent_stat_test.rb, test/services/ping_thing_user_stats_service_test.rb
- do not display stats in Ping Thing for users with 100% fail count
- run tests
- create only failed ping things for user
- run sidekiq (ping_thing_user_stats_worker)
- user data should not be displayed in a table 
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187386735)
=> 187386735-suppress-failing-users-in-pt

app/models/validator_ip.rb, app/services/blockchain/get_block_service.rb, config/schedule.rb, script/blockchain/check_error_slots.rb, test/services/blockchain/get_block_service_test.rb
- periodically check the slots with "response_error" status and make sure it has no block.
- run tests
- run `rails r daemons/blockchain/slot_subscribe_mainnet_daemon.rb` and wait until you get some slots with request error status
- run `sidekiq -q blockchain`
- run `rails r script/blockchain/check_error_slots.rb` (you may want to set delay time in the script before running)
- all of the "request_error" slots should be either "has_block" or "no block"
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187313301)
- [N] Does this PR add …
=> 187313301 process slots with missing blocks

test/services/update_avatar_file_service_test.rb
- there's an empty .png file being created while running test - this is not a correct behaviour
- run tests
- there should not be any .png files in the root directory after tests
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187568450)
=> 187568450-fix-create-png-file-test

app/services/blockchain/get_block_service.rb, app/services/blockchain/slot_subscribe_service.rb, config/sidekiq_blockchain.yml.example, script/blockchain/check_error_slots.rb
- create a separate blockchain for each network
- handle 429 error from rpcpool
- change your sidekiq_blockchain.yml file according to the example
- run sidekiq
- run `sidekiq -C config/sidekiq_blockchain.yml`
- run slot_subscribe daemons
- run script/blockchain/check_error_slots.rb
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/187641491)
=> 187641491 separate blockchanin queues

app/services/gatherers/vote_account_details_service.rb, daemons/gather_vote_account_details_daemon.rb
- fix ConnectionNotEstablished error handling for vote accounts daemon
- run `rails r daemons/gather_vote_account_details_daemon.rb`
- turn off mysql server
- it should retry 3 times and shut down afterwards
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188054694)
=> 188054694-fixConnectionNotEstablished-error-handling

app/views/layouts/_flash.html.erb
- there's a flash with "true" after user session expires - we don't need that
- 
- change `config.timeout_in` value in config/initializers/devise.rb to e.g. 1.minute
- log in
- after your session expires refresh the page
- there should be only one flash message about session expiration (no other flash with "true")
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188062372)
=> remove 'true' flash message

app/javascript/packs/validators/validator_details.vue
- if the validator is private but it's in testnet it's avatar should be visible
- check the validator details page for testnet and mainnet private validators - in testnet there should be a visible avatar, while in mainnet there should be a private validator icon
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188121107)
=> 188121107-fix-hidden-avatar

app/queries/validator_search_query.rb, test/queries/validator_query_test.rb
- ignores the whitespaces for the validator query, so both "test_name" and " test_name " returns the same search results
- run tests
- test the search in UI
- test the search in API
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188309334)
=> 188309334-sanitize-search

script/concerns/fix_data_center_module.rb, script/data_centers_scripts/fix_data_centers_webnx.rb
- add new addresses to webnx script and ignore inactive validators
- run tests
- run script/data_center_scripts/append_data_centers_geo_data.rb (preferably add another condition to query with webnx ip addresses)
- run script/data_centers_scripts/fix_data_centers_webnx.rb and check if the DC's where correctly updated
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188389002)
=> 188389002-fix-webnx-script

daemons/front_stats_update_daemon.rb
- rescue connection not established in front stats update daemon
- run `rails r daemons/front_stats_update_daemon.rb`
- stop mysql server
- daemon should exit
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188526101)
=> 188526101-mysql-error-handling-for-front-stats

app/controllers/api/v1/api_controller.rb, app/controllers/api/v1/ping_times_controller.rb, app/logic/collector_logic.rb, app/views/public/api_documentation.html.erb, test/logic/collector_logic_test.rb
- add max limit in API ping times request
- add validation to collector payload
- update docs
- remove unused code 
- run tests
- try both collector and ping_times endpoints
- try to provide incomplete payload to collector and make sure the data does not get saved
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/188704452)
=> 188704452-tweak-ping-times
